const data =  {
	arquitectura: [
		{
			"DENOMINACION": "GESTOR II",
			"NIVEL": "PROFESIONAL",
			"OPEC": "236916",
			"SALARIO": "$ 7,988,200.00",
			"VACANTES": "2",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 2",
			"ESTUDIO": "PROFESIONAL EN NBC: ARQUITECTURA",
			"EXPERIENCIA": "12 MESES PROFESIONAL",
			"FUNCIONES": `APLICAR HERRAMIENTAS DE SEGUIMIENTO, EVALUACION Y DIVULGACION DE LA PLANEACION INSTITUCIONAL Y LOS SISTEMAS DE GESTION, DE ACUERDO CON LA NORMATIVA VIGENTE, LA METODOLOGIA, LOS MEDIOS Y LINEAMIENTOS ESTABLECIDOS.
	EJECUTAR ACCIONES RELACIONADAS CON LA FORMULACION, SEGUIMIENTO, CONTROL, EVALUACION Y MEJORAMIENTO DE LOS PLANES, PROGRAMAS Y PROYECTOS DE LA DEPENDENCIA, SECCIONAL O PROCESO, DE ACUERDO CON LA NORMATIVA VIGENTE Y LA PLANEACION ESTRATEGICA DE LA ENTIDAD.
	GESTIONAR LA IMPLEMENTACION, MEJORA Y SEGUIMIENTO DE LOS SISTEMAS DE GESTION ESTABLECIDOS POR LA ENTIDAD, DE ACUERDO CON LA NORMATIVA LEGAL Y TECNICA, LAS DIRECTRICES INSTITUCIONALES Y LOS PROCEDIMIENTOS ESTABLECIDOS.
	GESTIONAR REQUERIMIENTOS RELACIONADOS CON POLITICAS Y ESTRATEGIAS PARA LA PLANEACION, FORMULACION, IMPLEMENTACION, MANTENIMIENTO Y EVALUACION DE CONVENIOS DE COOPERACION INTERNACIONAL E INTERINSTITUCIONAL, PARTICIPANDO EN SU DESARROLLO, DE ACUERDO CON LAS POLITICAS, LINEAMIENTOS, PROCEDIMIENTOS Y LAS NECESIDADES INSTITUCIONALES.
	LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO
	PREPARAR INFORMES ESTADISTICOS, DE GESTION DEL DESPACHO O SECCIONAL Y DE REQUERIMIENTOS PARA LA CONTRATACION DE SERVICIOS, DE ACUERDO CON LA NORMATIVA, LOS REGISTROS, LAS DIRECTRICES E INSTRUCCIONES IMPARTIDAS.`
		},
		{
			"DENOMINACION": "ANALISTA I",
			"NIVEL": "TECNICO",
			"OPEC": "242699",
			"SALARIO": "$ 4,083,784.00",
			"VACANTES": "1",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 1",
			"ESTUDIO": "APROBACION DOS AÑOS PROFESIONAL EN NBC: ARQUITECTURA / APROBACION DOS AÑOS TECNOLOGA EN NBC: ARQUITECTURA / DEMASIADAS CARRERAS",
			"EXPERIENCIA": "NO REQUIERE EXPERIENCIA",
			"FUNCIONES": `APOYAR A TODOS LOS SUBPROCESOS EN ACCIONES QUE FACILITEN LA PRESTACION DE LOS SERVICIOS GENERALES, TRANSPORTE, PROVISION DE BIENES Y SERVICIOS, EL ASEGURAMIENTO DE BIENES, LOS REQUERIMIENTOS DE INFRAESTRUCTURA, LA GESTION DOCUMENTAL, LA ADMINISTRACION Y CONTROL DE LOS BIENES MUEBLES DE PROPIEDAD DE LA DIAN, LOS ADQUIRIDOS, LOS ASIGNADOS Y LOS INMUEBLES QUE CONFORMAN SU PATRIMONIO Y LOS QUE SE RECIBAN EN DACION DE PAGO, DE ACUERDO CON LA NORMATIVA, LAS POLITICAS Y LOS PROCEDIMIENTOS VIGENTES.
	EJECUTAR ACTIVIDADES TECNICAS RELACIONADAS CON EL DESPACHO O SECCIONALES DE ACUERDO CON LOS LINEAMIENTOS NORMATIVOS Y TECNICOS, METODOLOGIA, PROCEDIMIENTOS.
	EJECUTAR LAS ACCIONES NECESARIAS PARA EL RECONOCIMIENTO Y ANALISIS DE LOS HECHOS ECONOMICOS, TALES COMO CERTIFICADO DE DISPONIBILIDAD PRESUPUESTAL, REGISTRO PRESUPUESTAL, REGISTRO DE RESERVAS, OBLIGACIONES PRESUPUESTALES, ORDENES DE PAGO, ETC., EN LOS SISTEMAS DE INFORMACION FINANCIERA, DE ACUERDO CON LOS PROCEDIMIENTOS, LA NORMATIVIDAD APLICABLE VIGENTE Y EL NIVEL Y EL GRADO DE RESPONSABILIDAD DEL EMPLEO.
	LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
	LLEVAR A CABO EL PROCESO DE ADMINISTRACION, INGRESO, CUSTODIA, DISPOSICION Y EGRESO DE LAS MERCANCIAS APREHENDIDAS, DECOMISADAS O ABANDONADAS A FAVOR DE LA NACION, DE BIENES MUEBLES ADJUDICADOS A LA NACION UAE DIAN EN PROCESOS DE COBRO COACTIVO Y PROCESOS CONCURSALES, ASI COMO LA COMERCIALIZACION DE BIENES Y SERVICIOS, DE ACUERDO LOS PROCEDIMIENTOS E INSTRUCTIVOS ESTABLECIDOS, LAS DIRECTRICES INSTITUCIONALES Y SU COMPETENCIA.
	PRACTICAR LA INSPECCION, CLASIFICACION, ALISTAMIENTO, DISPOSICION DE MERCANCIAS E INFORMES PERTINENTES, TENIENDO EN CUENTA EL ESTADO DE CONSERVACION DE LOS BIENES Y CONDICIONES DE ALMACENAMIENTO, ELABORANDO LOS SOPORTES RESPECTIVOS E INFORMES, DE ACUERDO CON LA NORMATIVA VIGENTE, LOS PROCEDIMIENTOS Y LOS INSTRUCTIVOS VIGENTES.
	PRESTAR APOYO TECNICO, ADMINISTRATIVO Y OPERATIVO RELACIONADO CON LA PLANEACION, DESARROLLO, CONTROL Y EVALUACION DE LOS COMPONENTES DEL DESPACHO, SUBPROCESOS, DE ACUERDO CON LOS REQUERIMIENTOS TECNICOS Y/O NORMATIVO , METODOLOGIAS, PROCEDIMIENTOS Y LINEAMIENTOS ESTABLECIDOS.
	PROCESAR INFORMACION RELACIONADA CON EL DESARROLLO Y EVALUACIONES DE PLANES, PROGRAMAS Y PROYECTOS DEL DESPACHO, SUBPROCESOS O AREA TENIENDO EN CUENTA LOS LINEAMIENTOS Y HERRAMIENTAS ESTABLECIDAS .
	PROYECTAR ACTOS ADMINISTRATIVOS Y DEMAS DOCUMENTOS DE CARACTER TECNICO, ADMINISTRATIVO Y OPERATIVO QUE DEFINAN SITUACIONES RELACIONADAS CON EL DESPACHO O SUBPROCESOS, DE ACUERDO CON LA NORMATIVA, COMPETENCIA, PROCEDIMIENTOS VIGENTES, NIVEL DE RESPONSABILIDAD DEL EMPLEO E INSTRUCCIONES IMPARTIDAS.
	REALIZAR ACTIVIDADES DE APOYO EN LA OPERACION Y MONITOREO DE LA PLATAFORMA, EL SOPORTE TECNICO Y LOS SERVICIOS DE INFORMACION DE LA ENTIDAD, DE ACUERDO CON LOS ESTANDARES, LINEAMIENTOS INSTITUCIONALES Y PROCEDIMIENTOS DEFINIDOS.`
		},
		{
			"DENOMINACION": "FACILITADOR II",
			"NIVEL": "ASISTENCIAL",
			"OPEC": "236904",
			"SALARIO": "$ 3,536,614.00",
			"VACANTES": "19",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 8; GIRARDOT 1; BUCARAMANGA 1; PALMRA 2; SAN ANDRES 1; BARRANQUILLA 1; POPAYAN 1; ARMENIA 1; MANIZALES 1; CALI 1; MEDELLIN 1",
			"ESTUDIO": "BACHILLERATO",
			"EXPERIENCIA": "12 MESES LABORAL",
			"FUNCIONES": `DAR APOYO LOGISTICO Y ADMINISTRATIVO EN LA EJECUCION DE OPERATIVOS, INSPECCIONES, CAMPAÑAS Y DEMAS ACTIVIDADES QUE SE PROGRAMEN Y DESARROLLEN DENTRO DE LOS PROCEDIMIENTOS QUE ATIENDE LA DEPENDENCIA, DE ACUERDO CON LOS PROCEDIMIENTOS VIGENTES.
	DESARROLLAR ACTIVIDADES DE TRANSFERENCIA, RECEPCION, ORGANIZACION, CLASIFICACION, CONSERVACION, CUSTODIA, PRESTAMO Y CONSULTA DE LAS SERIES Y O TIPOS DOCUMENTALES, DE ACUERDO CON LA NORMATIVA, PROCEDIMIENTOS E INSTRUMENTOS ARCHIVISTICOS ESTABLECIDOS.
	EJECUTAR LAS LABORES DE MENSAJERIA INTERNA Y EXTERNA QUE GARANTICE EL DESPACHO Y O RECIBO DE LAS COMUNICACIONES Y O DOCUMENTOS RELACIONADOS CON LOS PROCESOS QUE SE DESARROLLAN EN LA DEPENDENCIA, DE ACUERDO CON NORMATIVA, INSTRUCCIONES Y PROCEDIMIENTOS ESTABLECIDOS.
	LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
	REALIZAR ACCIONES DE APOYO EN LA EJECUCION Y CONTROL DEL INGRESO, SALIDA, PRESTAMO, TRASLADO, CONSERVACION Y ARCHIVO DE LA DOCUMENTACION, EXPEDIENTES, ELEMENTOS, CORRESPONDENCIA Y PUBLICACIONES DEL AREA, DE ACUERDO CON LAS NORMAS ESTABLECIDAS.
	REALIZAR LA PROYECCION Y ALISTAMIENTO DE DOCUMENTOS, INFORMES Y RESPUESTAS DE TIPO RUTINARIO QUE SE MANEJAN EN LA DEPENDENCIA ASIGNADA, DE ACUERDO CON SU NIVEL DE RESPONSABILIDAD, INSTRUCCIONES Y PROCEDIMIENTOS ESTABLECIDOS.`
		},
		{
			"DENOMINACION": "FACILITADOR I",
			"NIVEL": "ASISTENCIAL",
			"OPEC": "236908",
			"SALARIO": "$ 3,142,347.00",
			"VACANTES": "3",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 1; BARRANQUILLA 1; MEDELLIN 1",
			"ESTUDIO": "BACHILLERATO",
			"EXPERIENCIA": "NO REQUIERE EXPERIENCIA",
			"FUNCIONES": `BRINDAR INFORMACION A LOS CLIENTES INTERNOS Y EXTERNOS SOBRE TRAMITES Y SOLICITUDES A CARGO DE LA DEPENDENCIA, CONFORME CON LAS AUTORIZACIONES, NIVEL DE RESPONSABILIDAD DEL EMPLEO Y PROCEDIMIENTOS VIGENTES.
	DISTRIBUIR LOS ELEMENTOS DE CONSUMO A LOS FUNCIONARIOS, DE ACUERDO CON LOS REQUERIMIENTOS E INSTRUCCIONES INDICADOS POR SU SUPERIOR INMEDIATO.
	EJECUTAR LAS LABORES DE MENSAJERIA INTERNA Y EXTERNA QUE GARANTICE LA CLASIFICACION, EL DESPACHO Y O RECIBO DE LAS COMUNICACIONES, DOCUMENTOS, ELEMENTOS Y O EXPEDIENTES RELACIONADOS CON LOS PROCESOS QUE SE DESARROLLAN EN LA DEPENDENCIA, CONFORME CON LINEAMIENTOS Y PROCEDIMIENTOS ESTABLECIDOS.
	LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
	PREPARAR DOCUMENTOS, RESPUESTAS E INFORMES INHERENTES A LA EJECUCION DE LOS PROCEDIMIENTOS DEL AREA O PROCESO, DE ACUERDO CON INSTRUCCIONES Y LINEAMIENTOS ESTABLECIDOS.
	REALIZAR ACCIONES QUE PERMITAN LA EJECUCION DE OPERATIVOS, INSPECCIONES Y DEMAS ACTIVIDADES QUE SE DESARROLLEN EN EL PROCESO EN EL QUE SE DESEMPEÑA, PREVIA INSTRUCCION Y AUTORIZACION DEL SUPERIOR INMEDIATO.`
		},
		{
			"DENOMINACION": "FACILITADOR III",
			"NIVEL": "ASISTENCIAL",
			"OPEC": "236904",
			"SALARIO": "$ 3,980,025.00",
			"VACANTES": "39",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 12; BUCARAMANGA 2; BUENAVENTURA 3; MANIZALES 1; SAN ANDRES 1; CARTAGENA DE NDAS 2; BARRANQUILLA 2; MONTERIA 1; PALES 2; VALLEDUPAR 1; IPALES 1; CALI 3; ARMENA 2; INIRIDA 1; MEDELLIN 2; PUERTO ASIS 1; BARRANCABERMEJA 1; PEREIRA 1",
			"ESTUDIO": "BACHILLERATO",
			"EXPERIENCIA": "24 MESES LABORAL",
			"FUNCIONES": `EJECUTAR ACCIONES DE RECEPCION, RADICACION, ORGANIZACION Y DISTRIBUCION DE LA CORRESPONDENCIA QUE INGRESA O SALE DE LA DEPENDENCIA, DE ACUERDO CON LOS PROCEDIMIENTOS, INSTRUCCIONES Y LINEAMIENTOS ESTABLECIDOS.
	PREPARAR DOCUMENTOS, RESPUESTAS E INFORMES INHERENTES A LA GESTION DESARROLLADA EN LA DEPENDENCIA ASIGNADA, DE CONFORMIDAD CON LOS PROCEDIMIENTOS VIGENTES Y LAS INSTRUCCIONES IMPARTIDAS.
	EJECUTAR ACCIONES DE LOGISTICA, ADMINISTRATIVA Y OPERATIVAMENTE LAS ACCIONES RELACIONADAS CON LA EJECUCION DE LOS PROCEDIMIENTOS QUE SE DESARROLLAN DENTRO DEL PROCESO, DE ACUERDO CON LA ORGANIZACION INTERNA Y LOS LINEAMIENTOS VIGENTES.
	LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
	OPERAR LOS EQUIPOS Y ELEMENTOS MANUALES, MECANICOS O ELECTRONICOS, REQUERIDOS EN EL CUMPLIMIENTO DE LAS LABORES ASIGNADAS, DE ACUERDO CON LAS INSTRUCCIONES, LOS MANUALES DE OPERACION Y CONSERVACION Y LOS PROCEDIMIENTOS ESTABLECIDOS.
	PARTICIPAR EN LA RECOPILACION Y EL PROCESAMIENTO DE LA INFORMACION NECESARIA EN LA ELABORACION DE TRABAJOS, PROYECTOS E INFORMES, DE ACUERDO CON LAS DIRECTRICES ESTABLECIDAS Y LOS SISTEMAS DE INFORMACION DISPONIBLES.
	PROPORCIONAR INFORMACION, ORIENTACION Y/O RESPUESTAS DE CARACTER GENERAL O RUTINARIO, A LAS SOLICITUDES DE LOS CLIENTES INTERNOS Y EXTERNOS, QUE FACILITE EL DESARROLLO DE LOS PROCESOS INSTITUCIONALES, DE ACUERDO CON LA NORMATIVA , LOS PROTOCOLOS DE ATENCION Y SERVICIO Y LOS LINEAMIENTOS INSTITUCIONALES.
	REALIZAR ACCIONES DE VERIFICACION Y CONTROL DE LOS INVENTARIOS FISICOS DE LA DEPENDENCIA ASI COMO LOS TRAMITES ANTE LA INSTANCIA COMPETENTE, DE ACUERDO CON LOS PROCEDIMIENTOS ESTABLECIDOS.`
		},
		{
			"DENOMINACION": "FACILITADOR III",
			"NIVEL": "ASISTENCIAL",
			"OPEC": "242698",
			"SALARIO": "$ 3,980,025.00",
			"VACANTES": "2",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 2",
			"ESTUDIO": "BACHILLERATO",
			"EXPERIENCIA": "24 MESES LABORAL",
			"FUNCIONES": `RECOPILAR Y REGISTRAR LA INFORMACION Y DATOS QUE SOPORTEN LA GENERACION DE SOLUCIONES ANALITICAS,   DE CONFORMIDAD CON LOS REQUERIMIENTOS E INSTRUCCIONES IMPARTIDAS.
	ESCRIBIR CODIGOS DE PROGRAMACION RELACIONADOS CON LOS PROCESOS DE ANALITICA DE DATOS, DE ACUERDO CON METODOLOGIAS E INSTRUCCIONES IMPARTIDAS.
	PREPARAR LA INFORMACION Y LOS DATOS PARA EL ANALISIS MATEMATICO Y ESTADISTICO, COMO APOYO A LA IDENTIFICACION DE FENOMENOS Y COMPORTAMIENTOS DE POSIBLES INFRACCIONES E INCUMPLIMIENTOS A LA NORMATIVA TRIBUTARIA, ADUANERA Y CAMBIARIA, CONFORME CON LAS INSTRUCCIONES IMPARTIDAS.
	PREPARAR Y ORGANIZAR   LA INFORMACION Y LOS DATOS, PARA EL PERFILAMIENTO DE RIESGOS, LA SELECTIVIDAD ADUANERA Y DEMAS CONTROLES, DE ACUERDO CON LOS LINEAMIENTOS Y PROCEDIMIENTOS ESTABLECIDOS.
	ORGANIZAR INFORMACION PARA LA APLICACION DE SOLUCIONES DE ANALITICA QUE FACILITEN EL CUMPLIMIENTO DE LA GESTION INSTITUCIONAL, A TRAVES DEL APROVECHAMIENTO E INTEROPERABILIDAD DE LA INFORMACION, LA CIENCIA DE DATOS E INTELIGENCIA ARTIFICIAL, DE CONFORMIDAD CON LOS PROCEDIMIENTOS, METODOLOGIAS Y HERRAMIENTAS DEFINIDAS.
	LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.`
		},
		{
			"DENOMINACION": "ANALISTA III",
			"NIVEL": "TECNICO",
			"OPEC": "242701",
			"SALARIO": "$ 5,428,428.00",
			"VACANTES": "1",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 1",
			"ESTUDIO": "APROBACION DOS AÑOS PROFESIONAL EN NBC: ARQUITECTURA / APROBACION DOS AÑOS TECNOLOGA EN NBC: ARQUITECTURA / DEMASIADAS CARRERAS",
			"EXPERIENCIA": "24 MESES LABORAL",
			"FUNCIONES": `ADELANTAR EL PROCESO DE ADMINISTRACION, INGRESO, CUSTODIA, DISPOSICION Y EGRESO DE LAS MERCANCIAS APREHENDIDAS, DECOMISADAS O ABANDONADAS A FAVOR DE LA NACION, DE BIENES MUEBLES ADJUDICADOS A LA NACION-UAE DIAN EN PROCESOS DE COBRO COACTIVO Y PROCESOS CONCURSALES, ASI COMO LA COMERCIALIZACION DE BIENES Y SERVICIOS; DE ACUERDO CON LOS PROCEDIMIENTOS E INSTRUCTIVOS ESTABLECIDOS, LAS DIRECTRICES INSTITUCIONALES Y SU COMPETENCIA.
		APOYAR TECNICAMENTE EN LA EJECUCION DE LOS PRODUCTOS Y SERVICIOS DE TECNOLOGIAS DE LA INFORMACION Y LAS COMUNICACIONES DE LA ENTIDAD, DE ACUERDO CON LOS ESTANDARES, LINEAMIENTOS INSTITUCIONALES Y PROCEDIMIENTOS DEFINIDOS.
		DESARROLLAR LAS ACCIONES NECESARIAS PARA EL RECONOCIMIENTO Y ANALISIS DE LOS HECHOS ECONOMICOS, TALES COMO CERTIFICADO DE DISPONIBILIDAD PRESUPUESTAL, REGISTRO PRESUPUESTAL, REGISTRO DE RESERVAS, OBLIGACIONES PRESUPUESTALES, ORDENES DE PAGO, ETC., EN LOS SISTEMAS DE INFORMACION FINANCIERA, DE ACUERDO CON LOS PROCEDIMIENTOS, LA NORMATIVIDAD APLICABLE VIGENTE Y EL NIVEL Y EL GRADO DE RESPONSABILIDAD DEL EMPLEO.
		DESARROLLAR ACCIONES EN TODOS LOS SUBPROCESOS QUE FACILITEN LA PRESTACION DE LOS SERVICIOS GENERALES, DEL PARQUE AUTOMOTOR, PROVISION DE BIENES Y SERVICIOS, LOS REQUERIMIENTOS DE INFRAESTRUCTURA, EL ASEGURAMIENTO DE BIENES, LA GESTION DOCUMENTAL, LA ADMINISTRACION Y CONTROL DE LOS BIENES MUEBLES DE PROPIEDAD DE LA DIAN, LOS ADQUIRIDOS, LOS ASIGNADOS Y LOS INMUEBLES QUE CONFORMAN SU PATRIMONIO Y LOS QUE SE RECIBAN EN DACION DE PAGO, DE ACUERDO CON LA NORMATIVA, LAS POLITICAS Y LOS PROCEDIMIENTOS VIGENTES.
		EJECUTAR ACTIVIDADES TECNICAS RELACIONADAS CON EL DESPACHO O SECCIONALES DE ACUERDO CON LOS LINEAMIENTOS NORMATIVOS Y TECNICOS, METODOLOGIA Y PROCEDIMIENTOS.
		EJECUTAR LA INSPECCION, CLASIFICACION, ALISTAMIENTO, DISPOSICION DE MERCANCIAS E INFORMES PERTINENTES, TENIENDO EN CUENTA EL ESTADO DE CONSERVACION DE LOS BIENES Y CONDICIONES DE ALMACENAMIENTO, ELABORANDO LOS SOPORTES RESPECTIVOS E INFORMES, DE ACUERDO CON LA NORMATIVA VIGENTE, LOS PROCEDIMIENTOS Y LOS INSTRUCTIVOS VIGENTES.
		LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
		PRESTAR APOYO TECNICO, ADMINISTRATIVO Y OPERATIVO RELACIONADO CON LA PLANEACION, DESARROLLO, CONTROL Y EVALUACION DE LOS COMPONENTES DEL DESPACHO, SUBPROCESOS, DE ACUERDO CON LOS REQUERIMIENTOS TECNICOS Y/O NORMATIVOS, METODOLOGIAS, PROCEDIMIENTOS Y LINEAMIENTOS ESTABLECIDOS.
		PROCESAR INFORMACION RELACIONADA CON EL DESARROLLO Y EVALUACIONES DE PLANES, PROGRAMAS Y PROYECTOS DEL DESPACHO, SUBPROCESOS O AREA TENIENDO EN CUENTA LOS LINEAMIENTOS Y HERRAMIENTAS ESTABLECIDAS.
		PROYECTAR ACTOS ADMINISTRATIVOS Y DEMAS DOCUMENTOS DE CARACTER TECNICO, ADMINISTRATIVO Y OPERATIVO QUE DEFINAN SITUACIONES RELACIONADAS CON EL DESPACHO O SUBPROCESOS, DE ACUERDO CON LA NORMATIVA, COMPETENCIA, PROCEDIMIENTOS VIGENTES, NIVEL DE RESPONSABILIDAD DEL EMPLEO E INSTRUCCIONES IMPARTIDAS.`
		},
		{
			"DENOMINACION": "GESTOR III",
			"NIVEL": "PROFESIONAL",
			"OPEC": "242703",
			"SALARIO": "$ 9,346,562.00",
			"VACANTES": "3",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 2; SNCELEJO 1",
			"ESTUDIO": "PROFESIONAL EN NBC: ARQUITECTURA",
			"EXPERIENCIA": "12 MESES PROFESIONAL Y 12 MESES PROFESIONAL RELACIONADA",
			"FUNCIONES": `ADELANTAR PROCESOS DE ORIENTACION, IMPLEMENTACION, MEJORA Y SEGUIMIENTO EN EL CUMPLIMIENTO DE LOS PLANES, PROYECTOS Y SISTEMAS DE GESTION ESTABLECIDOS POR LA ENTIDAD, DE ACUERDO CON LA NORMATIVA LEGAL Y TECNICA, LAS DIRECTRICES INSTITUCIONALES Y LOS PROCEDIMIENTOS ESTABLECIDOS.
	CONTRIBUIR CON LA REVISION DE LOS REQUERIMIENTOS PARA LA CONTRATACION DE SERVICIOS O BIENES RELACIONADOS CON LA GESTION DEL DESPACHO, PROCESO O SECCIONAL, DE ACUERDO CON LA NORMATIVA VIGENTE, LOS PROCEDIMIENTOS ESTABLECIDOS, LAS ASIGNACIONES Y COMPETENCIA.
	IMPLEMENTAR POLITICAS Y ESTRATEGIAS PARA LA PLANEACION, FORMULACION, IMPLEMENTACION, MANTENIMIENTO Y EVALUACION DE CONVENIOS DE COOPERACION INTERNACIONAL E INTERINSTITUCIONAL, PARTICIPANDO EN SU DESARROLLO, DE ACUERDO CON LAS POLITICAS, LINEAMIENTOS, PROCEDIMIENTOS Y LAS NECESIDADES INSTITUCIONALES.
	LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO
	REALIZAR ACCIONES DE FORMULACION, EJECUCION, SEGUIMIENTO, AJUSTE Y EVALUACION DE LOS PLANES, PROGRAMAS O PROYECTOS DE LA DEPENDENCIA, PROCESO O SECCIONAL, DE ACUERDO CON LA NORMATIVA VIGENTE Y LA PLANEACION ESTRATEGICA DE LA ENTIDAD Y LA METODOLOGIA ESTABLECIDA.
	REALIZAR ACCIONES RELACIONADAS CON ANALISIS Y DIAGNOSTICOS DEL COMPORTAMIENTO DE LAS VARIABLES Y TENDENCIAS DE LOS SECTORES ECONOMICOS DE INFLUENCIA Y COMPETENCIA DE LA DEPENDENCIA, SECCIONAL O PROCESO, DE ACUERDO CON LA NORMATIVA, POLITICAS ECONOMICAS E INSTITUCIONALES, LINEAMIENTOS TECNICOS Y GRADO DE RESPONSABILIDAD DEL EMPLEO.`
		},
		{
			"DENOMINACION": "GESTOR III",
			"NIVEL": "PROFESIONAL",
			"OPEC": "236855",
			"SALARIO": "$ 9,346,562.00",
			"VACANTES": "6",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 5; BARRANQUILLA 1",
			"ESTUDIO": "PROFESIONAL EN NBC: ARQUTECTURA",
			"EXPERIENCIA": "12 MESES PROFESIONAL Y 12 MESES PROFESIONAL RELACIONADA",
			"FUNCIONES": `GESTIONAR LAS DIRECTRICES Y LINEAMIENTOS QUE SOPORTAN LA GESTION DE LOS SERVICIOS DE DATOS, DE ACUERDO A LOS ESTANDARES Y POLITICAS, ESTABLECIDOS EN EL GOBIERNO DE DATOS DE LA DIAN.
	VERIFICAR LOS RESULTADOS DE LA IMPLEMENTACION DE LAS ESTRATEGIAS TECNICAS DE OPTIMIZACION DE CAPACIDADES ANALITICAS Y USO EFICAZ DE LA INFORMACION, DE ACUERDO CON LOS LINEAMIENTOS DE GOBIERNO DE DATOS Y LA ARQUITECTURA DIGITAL DE LA DIAN.
	VERIFICAR EL CONTROL Y SEGUIMIENTO PERMANENTE A LA IMPLEMENTACION DE LOS LINEAMIENTOS QUE PERMITAN MANTENER LA INTEGRIDAD Y DISPONIBILIDAD DE LOS DATOS, DE ACUERDO CON LAS POLITICAS DE GOBIERNO DE DATOS Y LA ARQUITECTURA DIGITAL DE LA DIAN.
	ANALIZAR Y ESTABLECER LAS SOLUCIONES A LAS SOLICITUDES DE INFORMACION INTERNAS Y EXTERNAS CON EL FIN DE DETERMINAR LA VIABILIDAD DE SU GESTION, DE ACUERDO A LAS POLITICAS DE SEGURIDAD ESTABLECIDAS POR LA DIAN.
	GESTIONAR LAS SOLICITUDES DE LOS SERVICIOS DE DATOS Y LAS CAPACIDADES ANALITICAS RELACIONADOS CON LOS REPOSITORIOS DE DATOS,   DE ACUERDO CON LAS POLITICAS DE GOBIERNO DE DATOS, LA ARQUITECTURA DIGITAL DE LA DIAN Y LOS LINEAMIENTOS DE SEGURIDAD DE LA INFORMACION.
	OPERATIVIZAR LA ARQUITECTURA DE DATOS, Y SU MODELADO, QUE SIRVA DE BASE PARA EL DESARROLLO DE APLICACIONES Y REPOSITORIO UNICO DE DATOS, EN CUMPLIMIENTO DE LA POLITICA DE DATOS, LOS LINEAMIENTOS DE SEGURIDAD DE LA INFORMACION Y LA ARQUITECTURA DIGITAL DE LA ENTIDAD.
	LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.`
		},
		{
			"DENOMINACION": "Gestor III",
			"NIVEL": "PROFESIONAL",
			"OPEC": "236745",
			"SALARIO": "$ 9,346,562.00",
			"VACANTES": "2",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 1; SANTA MARTA 1",
			"ESTUDIO": "PROFESIONAL EN NBC: ARQUTECTURA",
			"EXPERIENCIA": "12 MESES PROFESIONAL Y 12 MESES PROFESIONAL RELACIONADA",
			"FUNCIONES": `GESTIONAR LAS ACCIONES NECESARIAS EN LA PRESTACION DE SERVICIOS GENERALES, GESTION DOCUMENTAL, TRANSPORTE Y PARQUE AUTOMOTOR, ADQUISICION Y SUMINISTRO DE BIENES Y SERVICIOS, ASEGURAMIENTO DE BIENES, ADMINISTRACION DE BIENES MUEBLES E INMUEBLES DE PROPIEDAD DE LA ENTIDAD, DE ACUERDO CON LA NORMATIVA VIGENTE Y LINEAMIENTOS INSTITUCIONALES.
	ATENDER TRAMITES, REQUERIMIENTOS, PETICIONES, QUEJAS, SUGERENCIAS, RECLAMOS Y DENUNCIAS DE ALTA COMPLEJIDAD RELACIONADOS CON TEMAS ADMINISTRATIVOS Y CONSULTAS TECNICAS, PROYECTANDO ACTOS ADMINISTRATIVOS Y DOCUMENTOS RELACIONADOS CON LA GESTION DEL PROCESO DE RECURSOS ADMINISTRATIVOS Y TRAMITAR LOS REQUERIMIENTOS DE TIPO AMBIENTAL DE LAS DIFERENTES SEDES DE LA DIAN Y DEL NIVEL CENTRAL, DE ACUERDO CON LA PLANEACION DEL AREA Y LOS LINEAMIENTOS INSTITUCIONALES.
	PROYECTAR CONCEPTOS TECNICOS DE TEMAS RELACIONADOS CON AREAS DE SU COMPETENCIA Y ADELANTAR LAS ACCIONES QUE VIABILICEN LA DISPOSICION Y/O ENAJENACION DE LOS BIENES INMUEBLES, DE ACUERDO CON LA NORMATIVA, DIRECTRICES Y PROCEDIMIENTOS VIGENTES.
	GESTIONAR LA SOLUCION A LOS REQUERIMIENTOS RELACIONADOS CON LA INFRAESTRUCTURA FISICA DE LA ENTIDAD Y LOS BIENES INMUEBLES RECIBIDOS EN PAGO DE OBLIGACIONES FISCALES, DE ACUERDO CON LA NORMATIVA, LAS POLITICAS, LOS RECURSOS ASIGNADOS, LAS NECESIDADES Y LOS PROCEDIMIENTOS ESTABLECIDOS.
	ATENDER LA DEMANDA DE INFRAESTRUCTURA, LA DOTACION Y EQUIPAMIENTO ELECTROMECANICO DE LAS DIFERENTES SECCIONALES Y DEPENDENCIAS DE LA ENTIDAD, REALIZANDO EL SEGUIMIENTO TECNICO, ADMINISTRATIVO Y FINANCIERO A LOS CONTRATOS ASIGNADOS COMO ENCARGADO DE BIENES INMUEBLES, DE ACUERDO CON LA NORMATIVA, LOS RECURSOS ASIGNADOS, LAS DIRECTRICES DEFINIDAS Y LOS PROCEDIMIENTOS VIGENTES.
	DESARROLLAR ACCIONES RELACIONADAS CON LOS PROCESOS DE SELECCION, ELABORACION, PERFECCIONAMIENTO Y LIQUIDACION DE LOS CONTRATOS REQUERIDOS POR LAS DIFERENTES AREAS DE LA ENTIDAD, Y VERIFICAR EL INCUMPLIMIENTO Y/O EFECTIVIDAD DE GARANTIAS, CONFORME A LA NORMATIVA Y PROCEDIMIENTOS ESTABLECIDOS.
	ADELANTAR DIAGNOSTICOS, ESTUDIOS PREVIOS O INVESTIGACIONES DE MEDIANA COMPLEJIDAD QUE PERMITAN CONTRATAR LA INTERVENCION, DOTACION, COMPRA, MEJORA O PRESTACION DE SERVICIOS, ELEMENTOS, EQUIPOS O INMUEBLES DEL AREA Y REALIZAR LA FORMULACION DE PROGRAMAS Y PROYECTOS DEL PROCESO DE RECURSOS ADMINISTRATIVOS Y/O LA DEPENDENCIA, DE ACUERDO CON NORMATIVA VIGENTE, POLITICAS GUBERNAMENTALES Y NECESIDADES INSTITUCIONALES.
	LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.`
		}
	],
	ingMecanica: [
		{
			"DENOMINACION": "GESTOR II",
			"NIVEL": "PROFESIONAL",
			"OPEC": "236785",
			"SALARIO": "$ 7,988,200.00",
			"VACANTES": "15",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 12; MEDELLIN 2; BUENAVENTURA 1",
			"ESTUDIO": "PROFESONAL EN NBC: INGENIERIA MECANICA",
			"EXPERIENCIA": "12 MESES PROFESIONAL",
			"FUNCIONES": `CONTROLAR EL CUMPLIMIENTO DE LOS REGIMENES ADUANEROS, ORIGEN, CLASIFICACION ARANCELARIA Y VALORACION DE LAS MERCANCIAS, OPERACIONES DE COMERCIO EXTERIOR EN ZONAS PRIMARIAS, ZONAS FRANCAS, MERCANCIAS EN ABANDONO, CUPOS O CONTINGENTES, EN EL MARCO DE LOS ACUERDOS COMERCIALES SUSCRITOS POR COLOMBIA Y LA COMPETENCIA INSTITUCIONAL.
CONTROLAR EL CUMPLIMIENTO Y MANTENIMIENTO DE LAS CONDICIONES, BENEFICIOS, REQUISITOS, OBLIGACIONES Y RESPONSABILIDADES DE LOS OPERADORES ECONOMICOS AUTORIZADOS Y USUARIOS ADUANEROS, DE ACUERDO CON LA NORMATIVA ADUANERA VIGENTE.
GESTIONAR LA APROBACION, ACEPTACION, CANCELACION Y CUSTODIA DE LAS GARANTIAS QUE AMPARAN LAS OBLIGACIONES PROPIAS DE LA GESTION ADUANERA DE CONFORMIDAD CON LA NORMATIVA VIGENTE.
GESTIONAR LAS OPERACIONES ADUANERAS DE INGRESO O SALIDA DE MERCANCIAS HACIA O DESDE EL TERRITORIO ADUANERO NACIONAL SOMETIDAS A LOS DIFERENTES REGIMENES, PREVIA VERIFICACION DEL CUMPLIMIENTO DE LOS REQUISITOS ESTABLECIDOS EN LAS NORMAS Y PROCEDIMIENTOS VIGENTES.
GESTIONAR LOS ACUERDOS NACIONALES O INTERNACIONALES DE INTERES PARA EL ESTADO COLOMBIANO EN MATERIA ADUANERA O DE COOPERACION, CON EL FIN DE QUE EL PAIS LOS SUSCRIBA O EFECTUE RESERVAS, DE CONFORMIDAD CON LINEAMIENTOS GUBERNAMENTALES Y NORMATIVA VIGENTE.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
ORIENTAR A LOS USUARIOS INTERNOS Y EXTERNOS EN LA APLICACION DE LAS NORMAS QUE REGULAN LA GESTION ADUANERA, EL CONTROL Y EL RECAUDO DE LOS TRIBUTOS ADUANEROS, DE ACUERDO CON LOS CRITERIOS TECNICOS-OPERATIVOS, LAS DIRECTRICES Y NORMATIVA VIGENTE QUE FACILITAN EL COMERCIO EXTERIOR.
REPRESENTAR A LA ENTIDAD EN REUNIONES NACIONALES E INTERNACIONALES RELACIONADAS CON EL COMERCIO EXTERIOR Y LA GESTION ADUANERA, ATENDIENDO LOS LINEAMIENTOS INSTITUCIONALES.
SUSTANCIAR LAS SOLICITUDES DE REGISTRO ADUANERO U OPERADOR ECONOMICO AUTORIZADO, ASI COMO LA INTERRUPCION, PERDIDA O CANCELACION DE LA CALIDAD, DE ACUERDO CON LA NORMATIVA ADUANERA.
SUSTANCIAR LAS SOLICITUDES EN MATERIA DE VALORACION ADUANERA, ORIGEN Y CLASIFICACION ARANCELARIA DE LAS MERCANCIAS, SEGUN LOS ACUERDOS COMERCIALES, TRATADOS DE LIBRE COMERCIO, SISTEMAS DE PREFERENCIAS Y NORMATIVA VIGENTE.`
		},
		{
			"DENOMINACION": "GESTOR II",
			"NIVEL": "PROFESIONAL",
			"OPEC": "236857",
			"SALARIO": "$ 7,988,200.00",
			"VACANTES": "3",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 3",
			"ESTUDIO": "PROFESONAL EN NBC: INGENIERIA MECANICA",
			"EXPERIENCIA": "12 MESES PROFESIONAL",
			"FUNCIONES": `EJECUTAR METODOLOGICAMENTE LAS DIRECTRICES Y LINEAMIENTOS QUE SOPORTAN LA GESTION DE LOS SERVICIOS DE DATOS DE ACUERDO A LOS ESTANDARES Y POLITICAS ESTABLECIDOS EN EL GOBIERNO DE DATOS DE LA DIAN.
CONSOLIDAR LOS RESULTADOS DE LA IMPLEMENTACION DE LAS ESTRATEGIAS TECNICAS DE OPTIMIZACION DE CAPACIDADES ANALITICAS Y USO EFICAZ DE LA INFORMACION, DE ACUERDO CON LOS LINEAMIENTOS DE GOBIERNO DE DATOS Y LA ARQUITECTURA DIGITAL DE LA DIAN.
APLICAR EL CONTROL Y SEGUIMIENTO PERMANENTE A LA IMPLEMENTACION DE LOS LINEAMIENTOS QUE PERMITAN MANTENER LA INTEGRIDAD Y DISPONIBILIDAD DE LOS DATOS, DE ACUERDO CON LAS POLITICAS DE GOBIERNO DE DATOS Y LA ARQUITECTURA DIGITAL DE LA DIAN.
GENERAR Y CONSOLIDAR REPORTES CONSULTANDO EL REPOSITORIO UNICO DE DATOS-DATAR, CON EL FIN DE ATENDER SOLICITUDES DE INFORMACION INTERNAS Y EXTERNAS, DE ACUERDO CON EL MANUAL DE POLITICAS Y LINEAMIENTOS DE SEGURIDAD DE LA INFORMACION DE LA DIAN.
INCORPORAR LOS SERVICIOS DE DATOS Y LAS CAPACIDADES ANALITICAS RELACIONADOS CON LOS REPOSITORIOS DE DATOS,   DE ACUERDO CON LAS POLITICAS DE GOBIERNO DE DATOS, LA ARQUITECTURA DIGITAL DE LA DIAN Y LOS LINEAMIENTOS DE SEGURIDAD DE LA INFORMACION.
ORGANIZAR Y GESTIONAR LA ARQUITECTURA DE DATOS, Y SU MODELADO, QUE SIRVA DE BASE PARA EL DESARROLLO DE APLICACIONES Y REPOSITORIO UNICO DE DATOS, EN CUMPLIMIENTO DE LA POLITICA DE DATOS, LOS LINEAMIENTOS DE SEGURIDAD DE LA INFORMACION Y LA ARQUITECTURA DIGITAL DE LA ENTIDAD.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.`
		},
		{
			"DENOMINACION": "GESTOR II",
			"NIVEL": "PROFESIONAL",
			"OPEC": "236863",
			"SALARIO": "$ 7,988,200.00",
			"VACANTES": "5",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 5",
			"ESTUDIO": "PROFESONAL EN NBC: INGENIERIA MECANICA",
			"EXPERIENCIA": "12 MESES PROFESIONAL",
			"FUNCIONES": `EJECUTAR LOS REQUERIMIENTOS DE APOYO TECNICO ESPECIALIZADO ASI COMO, BRINDAR SOLUCION DE INCIDENTES Y PROBLEMAS DE LOS SISTEMAS DE INFORMACION, SERVICIOS Y APLICATIVOS EN PRODUCCION, DE ACUERDO A LOS LINEAMIENTOS Y NORMATIVA VIGENTE.
EJECUTAR LAS ACTIVIDADES NECESARIAS DE ACOMPAÑAMIENTO EN EL DESARROLLO DEL CICLO DE VIDA DEL SOFTWARE, DE ACUERDO A LOS LINEAMIENTOS Y NORMATIVA VIGENTE.
VERIFICAR LAS SOLICITUDES Y REQUERIMIENTOS RELACIONADOS CON INSTRUMENTOS PARA LA IDENTIFICACION DE NECESIDADES, ESPECIFICACION DE REQUERIMIENTOS FUNCIONALES Y TECNICOS, LA ADMINISTRACION, LA CONSTRUCCION, LA IMPLANTACION, LA OPERACION, EL MANTENIMIENTO Y LA EVOLUCION DE SERVICIOS, DE ACUERDO A LOS LINEAMIENTOS Y NORMATIVA VIGENTE.
EFECTUAR AUDITORIAS CON EL FIN DE GARANTIZAR QUE EL SOFTWARE INSTALADO SEA PERMITIDO Y TENGA LICENCIA VIGENTE DE ACUERDO CON LOS LINEAMIENTOS Y PROCESOS ESTABLECIDOS POR LA ENTIDAD.
EJECUTAR LA OPERACION Y FUNCIONALIDAD DE LOS SISTEMAS DE INFORMACION EN PRODUCCION, DE ACUERDO A LOS LINEAMIENTOS Y NORMATIVA VIGENTE.
EFECTUAR EL MANTENIMIENTO Y ADMINISTRACION DE LAS APLICACIONES, EL CICLO DE DESARROLLO, LOS SERVICIOS DE INFORMACION, DE ACUERDO CON LA ARQUITECTURA DIGITAL, MANUAL DE SEGURIDAD DE LA INFORMACION Y POLITICAS DE GOBIERNO DE DATOS DE LA DIAN.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.`
		},
		{
			"DENOMINACION": "GESTOR II",
			"NIVEL": "PROFESIONAL",
			"OPEC": "236869",
			"SALARIO": "$ 7,988,200.00",
			"VACANTES": "2",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 2",
			"ESTUDIO": "PROFESONAL EN NBC: INGENIERIA MECANICA",
			"EXPERIENCIA": "12 MESES PROFESIONAL",
			"FUNCIONES": `EJECUTAR LAS ACCIONES PARA LA DISPONIBILIDAD Y MANTENIMIENTO DE LA PLATAFORMA TECNOLOGICA, DE ACUERDO CON LAS POLITICAS DE ADMINISTRACION, USO Y MEJORES PRACTICAS DE TI.
    GESTIONAR LOS EVENTOS DE LOS SISTEMAS GESTORES DE BASES DE DATOS (SGBD), PLATAFORMA DE PRODUCTIVIDAD CON TECNOLOGIA DE NUBE, DIRECTORIO ACTIVO, EL LICENCIAMIENTO ADQUIRIDO POR LA DIAN DE ACUERDO CON LAS POLITICAS , NORMAS Y ESTANDARES INSTITUCIONALES.
    PROYECTAR Y REALIZAR LAS ACCIONES NECESARIAS DE LA PLATAFORMA TECNOLOGICA DE LA DIAN ON PREMISE COMO CLOUD, DE ACUERDO CON LOS LINEAMIENTOS DEFINIDOS POR LA ENTIDAD, CUMPLIENDO ESTANDARES NACIONALES E INTERNACIONALES.
    APLICAR LOS ESTANDARES TECNICOS DE LOS ELEMENTOS DE LA PLATAFORMA DE TECNOLOGIA DE INFORMACION Y TELECOMUNICACIONES DE LA DIAN, DE ACUERDO CON LAS POLITICAS, LINEAMIENTOS, PROCEDIMIENTOS Y NECESIDADES INSTITUCIONALES.
    REALIZAR EL MONITOREO DE LA PLATAFORMA TECNOLOGICA Y LOS SERVICIOS DE INFORMACION Y APLICACIONES MEDIANTE ESTRATEGIAS DE RECUPERACION DE LOS SERVICIOS PRESTADOS A PARTIR DE INCIDENTES TECNOLOGICOS O DESASTRES, DE ACUERDO CON LOS PROCEDIMIENTOS ESTABLECIDOS.
    APLICAR LOS AJUSTES QUE SE REQUIEREN EN LOS DIFERENTES COMPONENTES DE LA PLATAFORMA TECNOLOGICA EN CUMPLIMIENTO DE LAS POLITICAS DE SEGURIDAD ESTABLECIDAS POR LA ENTIDAD.
    LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.`
		},
		{
			"DENOMINACION": "GESTOR II",
			"NIVEL": "PROFESIONAL",
			"OPEC": "236916",
			"SALARIO": "$ 7,988,200.00",
			"VACANTES": "2",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 2",
			"ESTUDIO": "PROFESONAL EN NBC: INGENIERIA MECANICA",
			"EXPERIENCIA": "12 MESES PROFESIONAL",
			"FUNCIONES": `APLICAR HERRAMIENTAS DE SEGUIMIENTO, EVALUACION Y DIVULGACION DE LA PLANEACION INSTITUCIONAL Y LOS SISTEMAS DE GESTION, DE ACUERDO CON LA NORMATIVA VIGENTE, LA METODOLOGIA, LOS MEDIOS Y LINEAMIENTOS ESTABLECIDOS.
EJECUTAR ACCIONES RELACIONADAS CON LA FORMULACION, SEGUIMIENTO, CONTROL, EVALUACION Y MEJORAMIENTO DE LOS PLANES, PROGRAMAS Y PROYECTOS DE LA DEPENDENCIA, SECCIONAL O PROCESO, DE ACUERDO CON LA NORMATIVA VIGENTE Y LA PLANEACION ESTRATEGICA DE LA ENTIDAD.
GESTIONAR LA IMPLEMENTACION, MEJORA Y SEGUIMIENTO DE LOS SISTEMAS DE GESTION ESTABLECIDOS POR LA ENTIDAD, DE ACUERDO CON LA NORMATIVA LEGAL Y TECNICA, LAS DIRECTRICES INSTITUCIONALES Y LOS PROCEDIMIENTOS ESTABLECIDOS.
GESTIONAR REQUERIMIENTOS RELACIONADOS CON POLITICAS Y ESTRATEGIAS PARA LA PLANEACION, FORMULACION, IMPLEMENTACION, MANTENIMIENTO Y EVALUACION DE CONVENIOS DE COOPERACION INTERNACIONAL E INTERINSTITUCIONAL, PARTICIPANDO EN SU DESARROLLO, DE ACUERDO CON LAS POLITICAS, LINEAMIENTOS, PROCEDIMIENTOS Y LAS NECESIDADES INSTITUCIONALES.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO
PREPARAR INFORMES ESTADISTICOS, DE GESTION DEL DESPACHO O SECCIONAL Y DE REQUERIMIENTOS PARA LA CONTRATACION DE SERVICIOS, DE ACUERDO CON LA NORMATIVA, LOS REGISTROS, LAS DIRECTRICES E INSTRUCCIONES IMPARTIDAS.`
		},
		{
			"DENOMINACION": "GESTOR I",
			"NIVEL": "PROFESIONAL",
			"OPEC": "236787",
			"SALARIO": "$ 6,811,546.00",
			"VACANTES": "5",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 2; CARTAGENA 1; CAL 1; LETCIA 1",
			"ESTUDIO": "PROFESONAL EN NBC: INGENIERIA MECANICA",
			"EXPERIENCIA": "NO REQUIERE EXPERIENCIA PERO SI CERTIFICADO DE INGLES NIVEL A2",
			"FUNCIONES": `ATENDER LAS OPERACIONES ADUANERAS DE INGRESO O SALIDA DE MERCANCIAS HACIA O DESDE EL TERRITORIO ADUANERO NACIONAL SOMETIDAS A LOS DIFERENTES REGIMENES, PREVIA VERIFICACION DEL CUMPLIMIENTO DE LOS REQUISITOS ESTABLECIDOS EN LAS NORMAS Y PROCEDIMIENTOS VIGENTES.
ATENDER LAS SOLICITUDES EN MATERIA DE VALORACION ADUANERA, ORIGEN Y CLASIFICACION ARANCELARIA DE LAS MERCANCIAS, SEGUN LOS ACUERDOS COMERCIALES, TRATADOS DE LIBRE COMERCIO, SISTEMAS DE PREFERENCIAS Y NORMATIVA VIGENTE.
CONTROLAR EL CUMPLIMIENTO DE LOS REGIMENES ADUANEROS, ORIGEN, CLASIFICACION ARANCELARIA Y VALORACION DE LAS MERCANCIAS, OPERACIONES DE COMERCIO EXTERIOR EN ZONAS PRIMARIAS, ZONAS FRANCAS, MERCANCIAS EN ABANDONO, CUPOS O CONTINGENTES EN EL MARCO DE LOS ACUERDOS COMERCIALES SUSCRITOS POR COLOMBIA Y LA COMPETENCIA INSTITUCIONAL.
CONTROLAR EL CUMPLIMIENTO Y MANTENIMIENTO DE LAS CONDICIONES, BENEFICIOS, REQUISITOS, OBLIGACIONES Y RESPONSABILIDADES DE LOS OPERADORES ECONOMICOS AUTORIZADOS Y USUARIOS ADUANEROS, DE ACUERDO CON LA NORMATIVA ADUANERA VIGENTE.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
ORIENTAR A LOS USUARIOS INTERNOS Y EXTERNOS EN LA APLICACION DE LAS NORMAS QUE REGULAN LA GESTION ADUANERA, EL CONTROL Y EL RECAUDO DE LOS TRIBUTOS ADUANEROS, DE ACUERDO CON LOS CRITERIOS TECNICOS-OPERATIVOS, LAS DIRECTRICES Y NORMATIVA VIGENTE QUE FACILITAN EL COMERCIO EXTERIOR.
PROYECTAR LA ACEPTACION, APROBACION Y CANCELACION DE LAS GARANTIAS QUE AMPARAN LAS OBLIGACIONES PROPIAS DE LA GESTION ADUANERA DE CONFORMIDAD CON LA NORMATIVA VIGENTE.
REPRESENTAR A LA ENTIDAD EN REUNIONES NACIONALES E INTERNACIONALES RELACIONADAS CON EL COMERCIO EXTERIOR Y LA GESTION ADUANERA, ATENDIENDO LOS LINEAMIENTOS INSTITUCIONALES.
TRAMITAR LAS SOLICITUDES DE REGISTRO ADUANERO U OPERADOR ECONOMICO AUTORIZADO, ASI COMO LA INTERRUPCION, PERDIDA O CANCELACION DE LA CALIDAD, DE ACUERDO CON LA NORMATIVA ADUANERA.`
		},
		{
			"DENOMINACION": "ANALISTA II",
			"NIVEL": "TECNICO",
			"OPEC": "236735",
			"SALARIO": "$ 4,655,747.00",
			"VACANTES": "6",
			"INSCRITOS": "",
			"CIUDADES": "IBAGUE 1; BOGOTA 3; NEIVA 1; BUENAVENTURA 1",
			"ESTUDIO": "APROBACION 3 AÑOS EN NBC: INGENERIA MECANICA / TECNICA PROFESOINAL EN NBC: INGENERA MECANICA / TERMINACION TECNOLOGA EN NBC: INGENIERIA MECANICA / VARAS CARRERAS",
			"EXPERIENCIA": "12 MESES LABORAL",
			"FUNCIONES": `ADELANTAR LABORES OPERATIVAS Y O ADMINISTRATIVAS REFERIDAS A LA GESTION DE INVENTARIOS Y PARQUE AUTOMOTOR PARA LOGRAR LOS OBJETIVOS PROPUESTOS DE CONFORMIDAD CON LA NORMATIVA VIGENTE Y APLICABLE.
APOYAR ACCIONES DE PRESTACION DE SERVICIOS GENERALES Y PQRS DE TIPO RUTINARIO, DE ACUERDO CON LA NORMATIVA Y LOS PROCEDIMIENTOS ESTABLECIDOS.
ATENDER LAS ESTRATEGIAS, MECANISMOS Y ACCIONES ENCAMINADAS A CUMPLIR LOS REQUERIMIENTOS DE INFRAESTRUCTURA DE ACUERDO CON LA NORMATIVA VIGENTE Y LAS DIRECTRICES INSTITUCIONALES.
EFECTUAR LA PUBLICACION, COMUNICACION, NOTIFICACION Y SEGUIMIENTO A LOS TERMINOS DE EJECUTORIA DE LOS ACTOS ADMINISTRATIVOS PROFERIDOS POR LA ENTIDAD, CON LA DEBIDA CERTIFICACION DEL TRAMITE SURTIDO, DE ACUERDO CON LA NORMATIVA Y PROCEDIMIENTOS ESTABLECIDOS.
EJECUTAR EL PROCESO DE INGRESO, DISPOSICION Y EGRESO DE LAS MERCANCIAS APREHENDIDAS, DECOMISADAS O ABANDONADAS A FAVOR DE LA NACION, DE BIENES MUEBLES ADJUDICADOS A LA NACION UAE DIAN EN PROCESOS DE COBRO COACTIVO Y PROCESOS CONCURSALES, ASI COMO LA COMERCIALIZACION DE BIENES Y SERVICIOS, DE ACUERDO CON LOS PROCEDIMIENTOS E INSTRUCTIVOS ESTABLECIDOS, LAS DIRECTRICES INSTITUCIONALES Y SU COMPETENCIA.
EJECUTAR LA INSPECCION, CLASIFICACION, ALISTAMIENTO, DISPOSICION DE MERCANCIAS E INFORMES PERTINENTES, TENIENDO EN CUENTA EL ESTADO DE CONSERVACION DE LOS BIENES Y CONDICIONES DE ALMACENAMIENTO, ELABORANDO LOS SOPORTES RESPECTIVOS, DE ACUERDO CON LA NORMATIVA, LOS PROCEDIMIENTOS Y LOS INSTRUCTIVOS VIGENTES.
EJECUTAR LAS ACCIONES Y ACTIVIDADES PERTINENTES PARA LA IMPLEMENTACION, ACTUALIZACION DE LOS INSTRUMENTOS ARCHIVISTICOS Y LAS ORIENTACIONES PARA SU APLICACION, ATENDIENDO LA NORMATIVA VIGENTE.
EJECUTAR LOS PROYECTOS DE LOGISTICA Y ADMINISTRACION, CUSTODIA, DISPOSICION DE MERCANCIAS APREHENDIDAS, DECOMISADAS O ABANDONADAS A FAVOR DE LA NACION Y BIENES MUEBLES ADJUDICADOS A LA NACION UAE DIAN EN PROCESOS DE COBRO COACTIVO Y PROCESOS CONCURSALES, DE ACUERDO CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
RECOPILAR LA INFORMACION DE INGRESOS Y EGRESOS CONTENIDA EN REPORTES, CONSOLIDACION DE INGRESOS, CERTIFICACION DE IVA, FACTURACION, CONTABILIZACION, VENTA DE MERCANCIAS, BIENES Y SERVICIOS, ENTRE OTROS, DE ACUERDO CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.
TRAMITAR LAS LABORES DE APOYO TECNICO Y ADMINISTRATIVO, RELACIONADAS CON LAS LABORES DE GESTION DOCUMENTAL, DEL PROCESO CONTRACTUAL Y REQUERIMIENTOS DE USUARIOS INTERNOS Y EXTERNOS, DE ACUERDO CON LA COMPETENCIA, LAS OBLIGACIONES EN LOS PROCEDIMIENTOS VIGENTES.`
		},
		{
			"DENOMINACION": "ANALISTA II",
			"NIVEL": "TECNICO",
			"OPEC": "236801",
			"SALARIO": "$ 4,655,747.00",
			"VACANTES": "2",
			"INSCRITOS": "",
			"CIUDADES": "IBAGUE 1; PEREIRA 1",
			"ESTUDIO": "APROBACION 3 AÑOS EN NBC: INGENERIA MECANICA / TECNICA PROFESOINAL EN NBC: INGENERA MECANICA / TERMINACION TECNOLOGA EN NBC: INGENIERIA MECANICA / VARAS CARRERAS",
			"EXPERIENCIA": "12 MESES LABORAL",
			"FUNCIONES": `ATENDER EL DIRECCIONAMIENTO, SEGUIMIENTO Y TRAMITE DE LAS PETICIONES, QUEJAS, SUGERENCIAS, RECLAMOS, FELICITACIONES Y DENUNCIAS ASIGNADAS POR EL SISTEMA, DE ACUERDO CON LA NORMATIVA VIGENTE Y PROCEDIMIENTOS ESTABLECIDOS.
ATENDER SOLICITUDES DE BAJA COMPLEJIDAD EN LA REALIZACION DE LAS CAMPAÑAS PROPIAS DEL SUBPROCESO DE ASISTENCIA AL USUARIO, O LAS INSTITUCIONALES, DE CONFORMIDAD CON LA NORMATIVA, COMPETENCIA, LINEAMIENTOS, PROCEDIMIENTOS VIGENTES E INSTRUCCIONES IMPARTIDAS.
ELABORAR DOCUMENTOS, HERRAMIENTAS Y DEMAS PRODUCTOS QUE FACILITEN LA COMPRENSION DE LA CULTURA DE LA CONTRIBUCION, DE ACUERDO CON LA NORMATIVA E INSTRUCCIONES IMPARTIDAS.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
REALIZAR ACCIONES Y PROPUESTAS DE NUEVAS ESTRATEGIAS QUE ASEGUREN  LA VERACIDAD Y CONFIABILIDAD DE LA INFORMACION INCORPORADA EN EL REGISTRO UNICO TRIBUTARIO, DE CONFORMIDAD CON LOS PROCEDIMIENTOS, PROTOCOLOS Y METODOLOGIAS ESTABLECIDAS.
RESPONDER LAS SOLICITUDES DE LOS USUARIOS EN TEMAS TRIBUTARIOS, ADUANEROS O CAMBIARIOS, A TRAVES DE LOS DIFERENTES CANALES, DE ACUERDO CON LA NORMATIVA Y PROCEDIMIENTOS ESTABLECIDOS.
TRAMITAR LAS SOLICITUDES DE INSCRIPCION O ACTUALIZACION EN EL REGISTRO UNICO TRIBUTARIO Y EL CONTROL A OBLIGACIONES FORMALES, DE CONFORMIDAD CON LA NORMATIVA Y PROCEDIMIENTOS VIGENTES.`
		},
		{
			"DENOMINACION": "GESTOR III",
			"NIVEL": "PROFESIONAL",
			"OPEC": "236855",
			"SALARIO": "$ 9,346,562.00",
			"VACANTES": "6",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 5; BARRANQUILLA 1",
			"ESTUDIO": "PROFESONAL EN NBC: INGENIERIA MECANICA",
			"EXPERIENCIA": "12 MESES PROFESIONAL Y 12 MESES PROFESIONAL RELACIONADA",
			"FUNCIONES": `GESTIONAR LAS DIRECTRICES Y LINEAMIENTOS QUE SOPORTAN LA GESTION DE LOS SERVICIOS DE DATOS, DE ACUERDO A LOS ESTANDARES Y POLITICAS, ESTABLECIDOS EN EL GOBIERNO DE DATOS DE LA DIAN.
VERIFICAR LOS RESULTADOS DE LA IMPLEMENTACION DE LAS ESTRATEGIAS TECNICAS DE OPTIMIZACION DE CAPACIDADES ANALITICAS Y USO EFICAZ DE LA INFORMACION, DE ACUERDO CON LOS LINEAMIENTOS DE GOBIERNO DE DATOS Y LA ARQUITECTURA DIGITAL DE LA DIAN.
VERIFICAR EL CONTROL Y SEGUIMIENTO PERMANENTE A LA IMPLEMENTACION DE LOS LINEAMIENTOS QUE PERMITAN MANTENER LA INTEGRIDAD Y DISPONIBILIDAD DE LOS DATOS, DE ACUERDO CON LAS POLITICAS DE GOBIERNO DE DATOS Y LA ARQUITECTURA DIGITAL DE LA DIAN.
ANALIZAR Y ESTABLECER LAS SOLUCIONES A LAS SOLICITUDES DE INFORMACION INTERNAS Y EXTERNAS CON EL FIN DE DETERMINAR LA VIABILIDAD DE SU GESTION, DE ACUERDO A LAS POLITICAS DE SEGURIDAD ESTABLECIDAS POR LA DIAN.
GESTIONAR LAS SOLICITUDES DE LOS SERVICIOS DE DATOS Y LAS CAPACIDADES ANALITICAS RELACIONADOS CON LOS REPOSITORIOS DE DATOS,   DE ACUERDO CON LAS POLITICAS DE GOBIERNO DE DATOS, LA ARQUITECTURA DIGITAL DE LA DIAN Y LOS LINEAMIENTOS DE SEGURIDAD DE LA INFORMACION.
OPERATIVIZAR LA ARQUITECTURA DE DATOS, Y SU MODELADO, QUE SIRVA DE BASE PARA EL DESARROLLO DE APLICACIONES Y REPOSITORIO UNICO DE DATOS, EN CUMPLIMIENTO DE LA POLITICA DE DATOS, LOS LINEAMIENTOS DE SEGURIDAD DE LA INFORMACION Y LA ARQUITECTURA DIGITAL DE LA ENTIDAD.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.`
		},
		{
			"DENOMINACION": "GESTOR III",
			"NIVEL": "PROFESIONAL",
			"OPEC": "242703",
			"SALARIO": "$ 9,346,562.00",
			"VACANTES": "3",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 2; SINCELEJO 1",
			"ESTUDIO": "PROFESONAL EN NBC: INGENIERIA MECANICA",
			"EXPERIENCIA": "12 MESES PROFESIONAL Y 12 MESES PROFESIONAL RELACIONADA",
			"FUNCIONES": `ADELANTAR PROCESOS DE ORIENTACION, IMPLEMENTACION, MEJORA Y SEGUIMIENTO EN EL CUMPLIMIENTO DE LOS PLANES, PROYECTOS Y SISTEMAS DE GESTION ESTABLECIDOS POR LA ENTIDAD, DE ACUERDO CON LA NORMATIVA LEGAL Y TECNICA, LAS DIRECTRICES INSTITUCIONALES Y LOS PROCEDIMIENTOS ESTABLECIDOS.
CONTRIBUIR CON LA REVISION DE LOS REQUERIMIENTOS PARA LA CONTRATACION DE SERVICIOS O BIENES RELACIONADOS CON LA GESTION DEL DESPACHO, PROCESO O SECCIONAL, DE ACUERDO CON LA NORMATIVA VIGENTE, LOS PROCEDIMIENTOS ESTABLECIDOS, LAS ASIGNACIONES Y COMPETENCIA.
IMPLEMENTAR POLITICAS Y ESTRATEGIAS PARA LA PLANEACION, FORMULACION, IMPLEMENTACION, MANTENIMIENTO Y EVALUACION DE CONVENIOS DE COOPERACION INTERNACIONAL E INTERINSTITUCIONAL, PARTICIPANDO EN SU DESARROLLO, DE ACUERDO CON LAS POLITICAS, LINEAMIENTOS, PROCEDIMIENTOS Y LAS NECESIDADES INSTITUCIONALES.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO
REALIZAR ACCIONES DE FORMULACION, EJECUCION, SEGUIMIENTO, AJUSTE Y EVALUACION DE LOS PLANES, PROGRAMAS O PROYECTOS DE LA DEPENDENCIA, PROCESO O SECCIONAL, DE ACUERDO CON LA NORMATIVA VIGENTE Y LA PLANEACION ESTRATEGICA DE LA ENTIDAD Y LA METODOLOGIA ESTABLECIDA.
REALIZAR ACCIONES RELACIONADAS CON ANALISIS Y DIAGNOSTICOS DEL COMPORTAMIENTO DE LAS VARIABLES Y TENDENCIAS DE LOS SECTORES ECONOMICOS DE INFLUENCIA Y COMPETENCIA DE LA DEPENDENCIA, SECCIONAL O PROCESO, DE ACUERDO CON LA NORMATIVA, POLITICAS ECONOMICAS E INSTITUCIONALES, LINEAMIENTOS TECNICOS Y GRADO DE RESPONSABILIDAD DEL EMPLEO.`
		},
		{
			"DENOMINACION": "ANALISTA V",
			"NIVEL": "TECNICO",
			"OPEC": "236732",
			"SALARIO": "$ 7,171,627.00",
			"VACANTES": "4",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 2; CAL 1; CUCUTA 1",
			"ESTUDIO": "TERMINACION Y APROBACION DE PROFESONAL EN NBC: IINGENERA MECANCA / TECNOLOGIA EN NBC: INGENERA MECANCA",
			"EXPERIENCIA": "24 MESES LABORAL Y 12 MESES RELACIONADA",
			"FUNCIONES": `ADELANTAR LA INSPECCION, CLASIFICACION, ALISTAMIENTO, DISPOSICION DE MERCANCIAS E INFORMES PERTINENTES, TENIENDO EN CUENTA EL ESTADO DE CONSERVACION DE LOS BIENES Y CONDICIONES DE ALMACENAMIENTO, ELABORANDO LOS SOPORTES RESPECTIVOS, DE ACUERDO CON LA NORMATIVA, LOS PROCEDIMIENTOS Y LOS INSTRUCTIVOS VIGENTES.
ADELANTAR LOS PROYECTOS DE LOGISTICA Y EJECUCION EN LA ADMINISTRACION, CUSTODIA, DISPOSICION DE MERCANCIAS APREHENDIDAS, DECOMISADAS O ABANDONADAS A FAVOR DE LA NACION Y BIENES MUEBLES ADJUDICADOS A LA NACION UAE DIAN EN PROCESOS DE COBRO COACTIVO Y PROCESOS CONCURSALES, DE ACUERDO CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.
ATENDER EL PROCESO DE INGRESO, DISPOSICION Y EGRESO DE LAS MERCANCIAS APREHENDIDAS, DECOMISADAS O ABANDONADAS A FAVOR DE LA NACION, DE BIENES MUEBLES ADJUDICADOS A LA NACION UAE DIAN EN PROCESOS DE COBRO COACTIVO Y PROCESOS CONCURSALES, ASI COMO LA COMERCIALIZACION DE BIENES Y SERVICIOS, DE ACUERDO CON LOS PROCEDIMIENTOS E INSTRUCTIVOS ESTABLECIDOS, LAS DIRECTRICES INSTITUCIONALES Y SU COMPETENCIA.
ATENDER LAS ESTRATEGIAS, MECANISMOS Y ACCIONES ENCAMINADAS A CUMPLIR LOS REQUERIMIENTOS DE INFRAESTRUCTURA DE ACUERDO CON LA NORMATIVA VIGENTE Y LAS DIRECTRICES INSTITUCIONALES.
EJECUTAR LABORES ADMINISTRATIVAS REFERIDAS A LA GESTION DE INVENTARIOS Y PARQUE AUTOMOTOR PARA LOGRAR LOS OBJETIVOS PROPUESTOS DE CONFORMIDAD CON LA NORMATIVA VIGENTE Y APLICABLE.
ELABORAR ACCIONES TECNICAS Y ADMINISTRATIVAS, CALCULOS Y PROYECCIONES DE RUBROS DE SERVICIOS GENERALES, ADEMAS DE CERTIFICACIONES, ACTAS Y DOCUMENTOS DE LA ACTIVIDAD DE LAS ETAPAS DE CONTRATACION DE ACUERDO CON LA NORMATIVA, POLITICAS Y LOS PROCEDIMIENTOS ESTABLECIDOS.
ELABORAR DOCUMENTOS RELACIONADOS CON LA GESTION CONTRACTUAL EN CADA UNA DE SUS ETAPAS, DE ACUERDO CON LA NORMATIVA VIGENTE Y PROCEDIMIENTOS ESTABLECIDOS EN LOS SUBPROCESOS DE ADQUISICION DE BIENES Y SERVICIOS.
ELABORAR LAS ACCIONES NECESARIAS QUE DEN TRAMITE A LA NOTIFICACION, COMUNICACION O PUBLICACION DE LOS ACTOS ADMINISTRATIVOS, DE ACUERDO CON LA NORMATIVA Y PROCEDIMIENTOS VIGENTES, REALIZANDO EL SEGUIMIENTO A LOS TERMINOS DE EJECUTORIA Y O LEVANTE DE FECHA DE EJECUTORIA MEDIANTE LA PROYECCION DE ACTO ADMINISTRATIVO QUE LO MOTIVE Y CERTIFICAR EL TRAMITE SURTIDO.
IMPLEMENTAR LAS ACCIONES Y ACTIVIDADES PERTINENTES PARA LA IMPLEMENTACION, ACTUALIZACION DE LOS INSTRUMENTOS ARCHIVISTICOS Y LAS ORIENTACIONES PARA SU APLICACION, ATENDIENDO LA NORMATIVA VIGENTE.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
REVISAR LA INFORMACION DE INGRESOS Y EGRESOS CONTENIDA EN REPORTES, CONSOLIDACION DE INGRESOS, CERTIFICACION DE IVA, FACTURACION, CONTABILIZACION, VENTA DE MERCANCIAS, BIENES Y SERVICIOS, ENTRE OTROS, DE ACUERDO CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.`
		},
		{
			"DENOMINACION": "ANALISTA IV",
			"NIVEL": "TECNICO",
			"OPEC": "236733",
			"SALARIO": "$ 6,390,426.00",
			"VACANTES": "4",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 1; PUERTO ASIS 1; BUENAVENTURA 1; PALMIRA 1",
			"ESTUDIO": "TERMINACION Y APROBACION DE PROFESONAL EN NBC: IINGENERA MECANCA / TECNOLOGIA EN NBC: INGENERA MECANCA",
			"EXPERIENCIA": "36 MESES LABORAL",
			"FUNCIONES": `ADELANTAR EL PROCESO DE INGRESO, DISPOSICION Y EGRESO DE LAS MERCANCIAS APREHENDIDAS, DECOMISADAS O ABANDONADAS A FAVOR DE LA NACION, DE BIENES MUEBLES ADJUDICADOS A LA NACION UAE DIAN EN PROCESOS DE COBRO COACTIVO Y PROCESOS CONCURSALES, ASI COMO LA COMERCIALIZACION DE BIENES Y SERVICIOS, DE ACUERDO CON LOS PROCEDIMIENTOS E INSTRUCTIVOS ESTABLECIDOS, LAS DIRECTRICES INSTITUCIONALES Y SU COMPETENCIA.
ADELANTAR LAS ACCIONES NECESARIAS QUE DEN TRAMITE A LA NOTIFICACION, COMUNICACION O PUBLICACION DE LOS ACTOS ADMINISTRATIVOS, REALIZANDO EL SEGUIMIENTO A LOS TERMINOS DE EJECUTORIA Y LA CERTIFICACION DEL TRAMITE SURTIDO, DE ACUERDO CON LA NORMATIVA Y PROCEDIMIENTOS VIGENTES.
ADELANTAR LAS ACCIONES Y ACTIVIDADES PERTINENTES PARA LA IMPLEMENTACION, ACTUALIZACION DE LOS INSTRUMENTOS ARCHIVISTICOS Y LAS ORIENTACIONES PARA SU APLICACION, ATENDIENDO LA NORMATIVA VIGENTE.
ATENDER LABORES ADMINISTRATIVAS REFERIDAS A LA GESTION DE INVENTARIOS Y PARQUE AUTOMOTOR PARA LOGRAR LOS OBJETIVOS PROPUESTOS DE CONFORMIDAD CON LA NORMATIVA VIGENTE Y APLICABLE.
ATENDER LAS ESTRATEGIAS, MECANISMOS Y ACCIONES ENCAMINADAS A CUMPLIR LOS REQUERIMIENTOS DE INFRAESTRUCTURA DE ACUERDO CON LA NORMATIVA VIGENTE Y LAS DIRECTRICES INSTITUCIONALES.
ATENDER REQUERIMIENTOS, SOLICITUDES RELACIONADAS CON LAS DIFERENTES ETAPAS DEL PROCESO CONTRACTUAL, DE CONFORMIDAD CON LAS DISPOSICIONES LEGALES SOBRE LA MATERIA.
CONSOLIDAR LA INFORMACION DE INGRESOS Y EGRESOS CONTENIDA EN REPORTES, CONSOLIDACION DE INGRESOS, CERTIFICACION DE IVA, FACTURACION, CONTABILIZACION, VENTA DE MERCANCIAS, BIENES Y SERVICIOS, ENTRE OTROS, DE ACUERDO CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.
EJECUTAR LAS ACCIONES DE PRESTACION DE SERVICIOS GENERALES, TECNICAS Y ADMINISTRATIVAS RELACIONADAS CON LOS CONTRATOS ASIGNADOS AL SUBPROCESO O AREA, ADEMAS DE LA PROYECCION DE LA RESPUESTA A LOS PQRS DE ACUERDO CON LAS NORMATIVAS Y LOS PROCEDIMIENTOS VIGENTES.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
LLEVAR A CABO LOS PROYECTOS DE LOGISTICA Y EJECUCION EN LA ADMINISTRACION, CUSTODIA, DISPOSICION DE MERCANCIAS APREHENDIDAS, DECOMISADAS O ABANDONADAS A FAVOR DE LA NACION Y BIENES MUEBLES ADJUDICADOS A LA NACION UAE DIAN EN PROCESOS DE COBRO COACTIVO Y PROCESOS CONCURSALES, DE ACUERDO CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.
PRACTICAR LA INSPECCION, CLASIFICACION, ALISTAMIENTO, DISPOSICION DE MERCANCIAS E INFORMES PERTINENTES, TENIENDO EN CUENTA EL ESTADO DE CONSERVACION DE LOS BIENES Y CONDICIONES DE ALMACENAMIENTO, ELABORANDO LOS SOPORTES RESPECTIVOS, DE ACUERDO CON LA NORMATIVA, LOS PROCEDIMIENTOS Y LOS INSTRUCTIVOS VIGENTES.`
		},
		{
			"DENOMINACION": "GESTOR III",
			"NIVEL": "PROFESIONAL",
			"OPEC": "236745",
			"SALARIO": "$ 9,346,562.00",
			"VACANTES": "2",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 1; SANTA MARTA 1",
			"ESTUDIO": "PROFESONAL EN NBC: INGENIERIA MECANICA",
			"EXPERIENCIA": "12 MESES PROFESIONAL Y 12 MESES RELACIONADA",
			"FUNCIONES": `GESTIONAR LAS ACCIONES NECESARIAS EN LA PRESTACION DE SERVICIOS GENERALES, GESTION DOCUMENTAL, TRANSPORTE Y PARQUE AUTOMOTOR, ADQUISICION Y SUMINISTRO DE BIENES Y SERVICIOS, ASEGURAMIENTO DE BIENES, ADMINISTRACION DE BIENES MUEBLES E INMUEBLES DE PROPIEDAD DE LA ENTIDAD, DE ACUERDO CON LA NORMATIVA VIGENTE Y LINEAMIENTOS INSTITUCIONALES.
ATENDER TRAMITES, REQUERIMIENTOS, PETICIONES, QUEJAS, SUGERENCIAS, RECLAMOS Y DENUNCIAS DE ALTA COMPLEJIDAD RELACIONADOS CON TEMAS ADMINISTRATIVOS Y CONSULTAS TECNICAS, PROYECTANDO ACTOS ADMINISTRATIVOS Y DOCUMENTOS RELACIONADOS CON LA GESTION DEL PROCESO DE RECURSOS ADMINISTRATIVOS Y TRAMITAR LOS REQUERIMIENTOS DE TIPO AMBIENTAL DE LAS DIFERENTES SEDES DE LA DIAN Y DEL NIVEL CENTRAL, DE ACUERDO CON LA PLANEACION DEL AREA Y LOS LINEAMIENTOS INSTITUCIONALES.
PROYECTAR CONCEPTOS TECNICOS DE TEMAS RELACIONADOS CON AREAS DE SU COMPETENCIA Y ADELANTAR LAS ACCIONES QUE VIABILICEN LA DISPOSICION Y/O ENAJENACION DE LOS BIENES INMUEBLES, DE ACUERDO CON LA NORMATIVA, DIRECTRICES Y PROCEDIMIENTOS VIGENTES.
GESTIONAR LA SOLUCION A LOS REQUERIMIENTOS RELACIONADOS CON LA INFRAESTRUCTURA FISICA DE LA ENTIDAD Y LOS BIENES INMUEBLES RECIBIDOS EN PAGO DE OBLIGACIONES FISCALES, DE ACUERDO CON LA NORMATIVA, LAS POLITICAS, LOS RECURSOS ASIGNADOS, LAS NECESIDADES Y LOS PROCEDIMIENTOS ESTABLECIDOS.
ATENDER LA DEMANDA DE INFRAESTRUCTURA, LA DOTACION Y EQUIPAMIENTO ELECTROMECANICO DE LAS DIFERENTES SECCIONALES Y DEPENDENCIAS DE LA ENTIDAD, REALIZANDO EL SEGUIMIENTO TECNICO, ADMINISTRATIVO Y FINANCIERO A LOS CONTRATOS ASIGNADOS COMO ENCARGADO DE BIENES INMUEBLES, DE ACUERDO CON LA NORMATIVA, LOS RECURSOS ASIGNADOS, LAS DIRECTRICES DEFINIDAS Y LOS PROCEDIMIENTOS VIGENTES.
DESARROLLAR ACCIONES RELACIONADAS CON LOS PROCESOS DE SELECCION, ELABORACION, PERFECCIONAMIENTO Y LIQUIDACION DE LOS CONTRATOS REQUERIDOS POR LAS DIFERENTES AREAS DE LA ENTIDAD, Y VERIFICAR EL INCUMPLIMIENTO Y/O EFECTIVIDAD DE GARANTIAS, CONFORME A LA NORMATIVA Y PROCEDIMIENTOS ESTABLECIDOS.
ADELANTAR DIAGNOSTICOS, ESTUDIOS PREVIOS O INVESTIGACIONES DE MEDIANA COMPLEJIDAD QUE PERMITAN CONTRATAR LA INTERVENCION, DOTACION, COMPRA, MEJORA O PRESTACION DE SERVICIOS, ELEMENTOS, EQUIPOS O INMUEBLES DEL AREA Y REALIZAR LA FORMULACION DE PROGRAMAS Y PROYECTOS DEL PROCESO DE RECURSOS ADMINISTRATIVOS Y/O LA DEPENDENCIA, DE ACUERDO CON NORMATIVA VIGENTE, POLITICAS GUBERNAMENTALES Y NECESIDADES INSTITUCIONALES.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.`
		},
		{
			"DENOMINACION": "ANALISTA III",
			"NIVEL": "TECNICO",
			"OPEC": "236776",
			"SALARIO": "$ 5,428,428.00",
			"VACANTES": "1",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 1",
			"ESTUDIO": "APROBACION DE 4 AÑOS PROFESIONAL EN NBC: INGENIERIA MECANICA / APROBACION Y TERMINACION DE TECNOLOGIA EN NBC: INGENERIA MECANICA",
			"EXPERIENCIA": "24 MESES LABORAL",
			"FUNCIONES": `ADELANTAR EL CONTROL EN EL CUMPLIMIENTO DE LOS REQUISITOS, OBLIGACIONES Y RESPONSABILIDADES DE LOS USUARIOS DE LA GESTION ADUANERA, DE ACUERDO CON LOS LINEAMIENTOS INSTITUCIONALES Y NORMATIVA VIGENTE.
ADELANTAR EL CUMPLIMIENTO Y MANTENIMIENTO DE LAS CONDICIONES, BENEFICIOS, REQUISITOS, OBLIGACIONES Y RESPONSABILIDADES DE LOS OPERADORES ECONOMICOS AUTORIZADOS Y USUARIOS ADUANEROS, DE ACUERDO CON LA NORMATIVA ADUANERA VIGENTE.
ADELANTAR EL TRAMITE DE LA ACEPTACION, APROBACION Y CANCELACION DE LAS GARANTIAS QUE AMPARAN LAS OBLIGACIONES PROPIAS DE LA GESTION ADUANERA DE CONFORMIDAD CON LA NORMATIVA VIGENTE.
ADELANTAR EL TRAMITE DE LAS SOLICITUDES DE REGISTRO ADUANERO U OPERADOR ECONOMICO AUTORIZADO, ASI COMO LA INTERRUPCION, PERDIDA O CANCELACION DE LA CALIDAD, DE ACUERDO CON LA NORMATIVA ADUANERA.
ADELANTAR LOS REQUERIMIENTOS EN MATERIA DE VALORACION ADUANERA, ORIGEN Y CLASIFICACION ARANCELARIA DE LAS MERCANCIAS, SEGUN LA NORMATIVA VIGENTE Y LINEAMIENTOS IMPARTIDOS.
ATENDER AL USUARIO INTERNO Y EXTERNO EN LOS TRAMITES RELACIONADAS CON LA GESTION ADUANERA, DE ACUERDO A LAS DIRECTRICES Y NORMATIVA VIGENTE.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.`
		},
		{
			"DENOMINACION": "GESTOR III",
			"NIVEL": "PROFESIONAL",
			"OPEC": "236861",
			"SALARIO": "$ 9,346,562.00",
			"VACANTES": "8",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 7; MEDELLIN 1",
			"ESTUDIO": "PROFESONAL EN NBC: INGENIERIA MECANICA",
			"EXPERIENCIA": "12 MESES PROFESIONAL Y 12 MESES PROFESIONAL RELACIONADA",
			"FUNCIONES": `REALIZAR Y APOYAR EL SEGUIMIENTO, VERIFICAR, PRUEBAS TECNICO -FUNCIONALES DE LOS SERVICIOS INFORMATICOS ELECTRONICOS DE TAL MANERA QUE SE OBTENGA CALIDAD DE LOS PRODUCTOS ENTREGADOS DE ACUERDO A LOS LINEAMIENTOS Y NORMATIVA VIGENTE.
GESTIONAR LAS ACTIVIDADES NECESARIAS DE ACOMPAÑAMIENTO EN EL DESARROLLO DEL CICLO DE VIDA DEL SOFTWARE, DE ACUERDO A LOS LINEAMIENTOS Y NORMATIVA VIGENTE.
GESTIONAR EL ANALISIS Y DISEÑO DE SOFTWARE DE CALIDAD Y EN OPORTUNIDAD ESTABLECIDA EN EL PLAN DE TRABAJO, DE LOS PROYECTOS DE SOFTWARE ASIGNADOS, DE ACUERDO A LOS LINEAMIENTOS Y NORMATIVA VIGENTE.
APOYAR LAS ACTIVIDADES RELACIONADAS CON EL INVENTARIO DE EQUIPOS A NIVEL NACIONAL Y REALIZAR SEGUIMIENTO A LAS DIRECCIONES SECCIONALES, DE ACUERDO CON LOS LINEAMIENTOS Y LA NORMATIVA VIGENTE.
DAR SOLUCION EN EL DESARROLLO SOBRE LA OPERACION Y FUNCIONALIDAD DE LOS SISTEMAS DE INFORMACION EN PRODUCCION, DE ACUERDO A LOS LINEAMIENTOS Y NORMATIVA VIGENTE.
COORDINAR EL MANTENIMIENTO Y ADMINISTRACION DE LAS APLICACIONES, EL CICLO DE DESARROLLO, LOS SERVICIOS DE INFORMACION, DE ACUERDO CON LA ARQUITECTURA DIGITAL, MANUAL DE SEGURIDAD DE LA INFORMACION Y POLITICAS DE GOBIERNO DE DATOS DE LA DIAN.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.`
		},
		{
			"DENOMINACION": "GESTOR IV",
			"NIVEL": "PROFESIONAL",
			"OPEC": "236781",
			"SALARIO": "$ 9,862,811.00",
			"VACANTES": "1",
			"INSCRITOS": "",
			"CIUDADES": "BOGOTA 1",
			"ESTUDIO": "PROFESONAL EN NBC: INGENIERIA MECANICA",
			"EXPERIENCIA": "12 MESES PROFESONAL Y 24 MESES PROFESIONAL RELACIONADA Y CERTFICADO DE INGLES NIVEL A2",
			"FUNCIONES": `MONITOREAR LAS GARANTIAS APROBADAS Y/O ACEPTADAS EN CUMPLIMIENTO DE LAS OBLIGACIONES PROPIAS DE LA GESTION ADUANERA, EFECTUANDO SU TRAZABILIDAD, DE CONFORMIDAD CON LA NORMATIVA Y PROCEDIMIENTOS VIGENTES.
    CONTROLAR EL CUMPLIMIENTO DE LOS REGIMENES ADUANEROS, ORIGEN, CLASIFICACION ARANCELARIA Y VALORACION DE LAS MERCANCIAS, OPERACIONES DE COMERCIO EXTERIOR EN ZONAS PRIMARIAS, ZONAS FRANCAS, MERCANCIAS EN ABANDONO, CUPOS O CONTINGENTES EN EL MARCO DE LOS ACUERDOS COMERCIALES SUSCRITOS POR COLOMBIA Y LA COMPETENCIA INSTITUCIONAL.
    GESTIONAR LAS SOLICITUDES DE REGISTRO ADUANERO U OPERADOR ECONOMICO AUTORIZADO, ASI COMO LA INTERRUPCION, PERDIDA O CANCELACION DE LA CALIDAD, DE ACUERDO CON LA NORMATIVA ADUANERA.
    GESTIONAR LAS SOLICITUDES EN MATERIA DE VALORACION ADUANERA, ORIGEN Y CLASIFICACION ARANCELARIA DE LAS MERCANCIAS, SEGUN LOS ACUERDOS COMERCIALES, TRATADOS DE LIBRE COMERCIO, SISTEMAS DE PREFERENCIAS Y NORMATIVA VIGENTE.
    LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
    MONITOREAR EL CUMPLIMIENTO Y MANTENIMIENTO DE LAS CONDICIONES, BENEFICIOS, REQUISITOS, OBLIGACIONES Y RESPONSABILIDADES DE LOS OPERADORES ECONOMICOS AUTORIZADOS Y USUARIOS ADUANEROS, DE ACUERDO CON LA NORMATIVA ADUANERA VIGENTE.
    MONITOREAR LAS OPERACIONES ADUANERAS DE INGRESO O SALIDA DE MERCANCIAS HACIA O DESDE EL TERRITORIO ADUANERO NACIONAL SOMETIDAS A LOS DIFERENTES REGIMENES, PREVIA VERIFICACION DEL CUMPLIMIENTO DE LOS REQUISITOS ESTABLECIDOS EN LAS NORMAS Y PROCEDIMIENTOS VIGENTES.
    ORIENTAR A LOS USUARIOS INTERNOS Y EXTERNOS EN LA APLICACION DE LAS NORMAS QUE REGULAN LA GESTION ADUANERA, EL CONTROL Y EL RECAUDO DE LOS TRIBUTOS ADUANEROS, DE ACUERDO CON LOS CRITERIOS TECNICOS-OPERATIVOS, LAS DIRECTRICES Y NORMATIVA VIGENTE QUE FACILITAN EL COMERCIO EXTERIOR.
    PROYECTAR LA SUSCRIPCION O EFECTUAR RESERVAS A LOS ACUERDOS NACIONALES O INTERNACIONALES EN MATERIA ADUANERA O DE COOPERACION, DE ACUERDO CON LINEAMIENTOS GUBERNAMENTALES Y NORMATIVA VIGENTE.
    REPRESENTAR A LA ENTIDAD EN REUNIONES NACIONALES E INTERNACIONALES RELACIONADAS CON EL COMERCIO EXTERIOR Y LA GESTION ADUANERA, ATENDIENDO LOS LINEAMIENTOS INSTITUCIONALES.`
		}
	]
};




const empleosContainer = document.querySelector("#empleos-container");
const selectEmpleos = document.querySelector("#select-empleos");

/**
 * Función auxiliar para convertir el texto largo de funciones en una lista (<ul>) de elementos (<li>).
 * @param {string} rawText El bloque de texto con saltos de línea.
 * @returns {HTMLUListElement} El elemento <ul> generado.
 */

function crearFuncionesLista(rawText) {
	const ul = document.createElement('ul');
    ul.classList.add('funciones-list');

    // Divide el texto por saltos de línea o por punto y seguido, luego filtra líneas vacías.
    const funcionesArray = rawText.split('\n').filter(line => line.trim() !== '');

    funcionesArray.forEach(funcText => {
        const li = document.createElement('li');
        li.textContent = funcText.trim();
        ul.appendChild(li);
    });

    return ul;
}

function crearEmpleo(item) {
	const card = document.createElement("div");
	card.classList.add("card");

	const titulo = document.createElement("h3");
	titulo.textContent = item.DENOMINACION;

	const subtitulo = document.createElement("p");
	subtitulo.classList.add("empleo-nivel");
	subtitulo.textContent = `Nivel ${item.NIVEL} | OPEC: ${item.OPEC}`;

	const detallesDiv = document.createElement("div");
	detallesDiv.classList.add("empleo-detalles");

	const salario = document.createElement("p");
	salario.classList.add("salario");
	salario.textContent = `Salario: ${item.SALARIO}`;

	const ciudades = document.createElement("p");
	ciudades.textContent = `Ciudades: ${item.CIUDADES}`;

    const vacantes = document.createElement("p");
	vacantes.textContent = `Vacantes: ${item.VACANTES}`;

    const inscritos = document.createElement("p");
	inscritos.textContent = `Inscritos: ${item.INSCRITOS}`;

    vacantes.classList.add("negrilla-big");
    inscritos.classList.add("negrilla-big");

	detallesDiv.appendChild(salario);
	detallesDiv.appendChild(vacantes);
	detallesDiv.appendChild(inscritos);
	detallesDiv.appendChild(ciudades);

	const requisitosDiv = document.createElement("div");
	requisitosDiv.classList.add("empleo-requisitos");

	const estudio = document.createElement("p");
	estudio.textContent = `Estudio: ${item.ESTUDIO}`;

	const experiencia = document.createElement("p");
	experiencia.textContent = `Experiencia: ${item.EXPERIENCIA}`;

	requisitosDiv.appendChild(estudio);
	requisitosDiv.appendChild(experiencia);

	const funcionesTitulo = document.createElement("h4");
	funcionesTitulo.textContent = "Funciones del Empleo";

    const funcionesLista = crearFuncionesLista(item.FUNCIONES || '');


	card.appendChild(titulo);
	card.appendChild(subtitulo);
	card.appendChild(detallesDiv);
	card.appendChild(requisitosDiv);
	card.appendChild(funcionesTitulo);
	card.appendChild(funcionesLista);

    return card;

}

function renderizarEmpleos(listaEmpleos) {
	//limpiar el contenido de los empleos anteriores (si tenia)
	while (empleosContainer.firstChild) {
		empleosContainer.removeChild(empleosContainer.firstChild);
	}

	//crear empleo
	listaEmpleos.forEach(empleo => {
		const empleoCard = crearEmpleo(empleo);
		empleosContainer.appendChild(empleoCard);
	})
}


