const data = [
  {
    "DENOMINACION": "GESTOR I",
    "NIVEL": "PROFESIONAL",
    "OPEC": "236611",
    "SALARIO": "$ 6,811,546.00",
    "VACANTES": "57",
    "CIUDADES": "BOGOTA 13; SAN ANDRES 3; ARMENIA 1; BARRANQUILLA 5; PEREIRA 3; BUCARAMANGA 4; TUNJA 1; TULUA 2; POPAYAN 1; SINCELEJO 1; SANTA MARTA 2; TURBO 1; MANIZALES 1; YOPAL 1; VALLEDUPAR 1; CARTAGENA INDIAS 4; MEDELLIN 1; MAICAO 1; VILLAVICENCIO 1; CUCUTA 3; CALI 5; BUENAVENTURA 1; MONTERIA 1",
    "ESTUDIO": "PROFESIONAL EN NBC: CONTADURIA PUBLICA",
    "EXPERIENCIA": "NO REQUIERE EXPERIENCIA",
	"FUNCIONES": `ELABORAR INFORMES ESTADISTICOS Y DE GESTION REQUERIDOS, DE ACUERDO CON LOS PROCEDIMIENTOS ESTABLECIDOS Y LAS DIRECTRICES INSTITUCIONALES.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
PARTICIPAR EN LA EJECUCION DE ACCIONES DE FISCALIZACION, EN EL MARCO DE SU COMPETENCIA Y JURISDICCION, TENDIENTES A LA VERIFICACION DEL CUMPLIMIENTO DE LAS OBLIGACIONES TRIBUTARIAS, ADUANERAS O CAMBIARIAS, DE ACUERDO CON LA NORMATIVA VIGENTE, LINEAMIENTOS INSTITUCIONALES Y PROCEDIMIENTOS ESTABLECIDOS.
PARTICIPAR EN LAS DILIGENCIAS DE DESTRUCCION DE MERCANCIA AVERIADA, DEFECTUOSA O IMPROPIA RESPECTO DEL FIN PARA EL CUAL FUE IMPORTADA, DE ACUERDO CON LA NORMATIVA VIGENTE, LOS PROCEDIMIENTOS ESTABLECIDOS Y LAS DIRECTRICES INSTITUCIONALES.
PLANIFICAR LA LOGISTICA PARA LA EJECUCION DE ACCIONES DE CONTROL, DE TAL FORMA QUE PERMITA ALCANZAR LOS RESULTADOS ESPERADOS, DE ACUERDO CON LOS LINEAMIENTOS INSTITUCIONALES.
PROFERIR LOS ACTOS ADMINISTRATIVOS DE TRAMITE, PREPARATORIOS Y DE FONDO REQUERIDOS DENTRO DEL PROCESO, DE ACUERDO CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.
REALIZAR INVESTIGACIONES PARA DETERMINAR EL CUMPLIMIENTO DE LAS OBLIGACIONES TRIBUTARIAS, ADUANERAS O CAMBIARIAS Y, EL REPORTE DE LAS OPERACIONES SOSPECHOSAS DE LAVADO DE ACTIVOS Y FINANCIACION DEL TERRORISMO, EN EL MARCO DE SU COMPETENCIA Y JURISDICCION, DE ACUERDO CON LA NORMATIVA VIGENTE, LAS DIRECTRICES INSTITUCIONALES Y LOS PROCEDIMIENTOS ESTABLECIDOS.`
  },
  {
    "DENOMINACION": "GESTOR I",
    "NIVEL": "PROFESIONAL",
    "OPEC": "236642",
    "SALARIO": "$ 6,811,546.00",
    "VACANTES": "3",
    "CIUDADES": "IBAGUE 1; BUENAVENTURA 1; NEIVA 1",
    "ESTUDIO": "PROFESIONAL EN NBC: CONTADURIA PUBLICA",
    "EXPERIENCIA": "NO REQUIERE EXPERIENCIA",
	"FUNCIONES": `ADELANTAR ACCIONES DE EJECUCION Y ACTUALIZACION DE ESTANDARES, ESTRATEGIAS, PROCEDIMIENTOS Y MECANISMOS DE DIVULGACION DE INFORMACION DE COMPETENCIA DEL SUBPROCESO DE ASISTENCIA AL USUARIO, DE ACUERDO CON LA NORMATIVA, POLITICAS GUBERNAMENTALES Y PROCEDIMIENTOS ESTABLECIDOS.
ATENDER LAS SOLICITUDES RELACIONADAS CON LA INSCRIPCION Y ACTUALIZACION DEL REGISTRO UNICO TRIBUTARIO Y EL CONTROL A LAS OBLIGACIONES FORMALES, DE CONFORMIDAD CON LA NORMATIVA Y PROCEDIMIENTOS VIGENTES.
ATENDER LAS SOLICITUDES Y PETICIONES DE LA CIUDADANIA RELATIVAS A TEMAS TRIBUTARIOS, ADUANEROS Y CAMBIARIOS, DE ACUERDO CON LA NORMATIVA, POLITICAS, LINEAMIENTOS INSTITUCIONALES, PROCEDIMIENTOS ESTABLECIDOS.
EJECUTAR ACCIONES QUE FOMENTEN LA CULTURA DE LA CONTRIBUCION DE ACUERDO CON LA NORMATIVA, POLITICAS Y CONVENIOS ESTABLECIDOS.
EJECUTAR ESTRATEGIAS DE SERVICIO, CAMPAÑAS Y DEMAS ACCIONES DE GESTION PERSUASIVA TENDIENTES A LA DIFUSION Y CUMPLIMIENTO DE OBLIGACIONES TRIBUTARIAS, ADUANERAS Y CAMBIARIAS, DE CONFORMIDAD CON LA NORMATIVA, COMPETENCIA, LINEAMIENTOS Y PROCEDIMIENTOS VIGENTES.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
REALIZAR CLASIFICACION, ASIGNACION, DIRECCIONAMIENTO Y SEGUIMIENTO DE PETICIONES, QUEJAS, SUGERENCIAS, RECLAMOS, FELICITACIONES Y DENUNCIAS, DE ACUERDO CON LA NORMATIVA VIGENTE, EL SISTEMA DE GESTION Y PROCEDIMIENTOS ESTABLECIDOS.`
  },
  {
    "DENOMINACION": "ANALISTA III",
    "NIVEL": "TECNICO",
    "OPEC": "236651",
    "SALARIO": "$ 5,428,428.00",
    "VACANTES": "16",
    "CIUDADES": "IBAGUE 1; BOGOTA 5; BUCARAMANGA 1; SANTA MARTA 1; BARRANQUILLA 3; QUIBDO 1; MANIZALES 1; CARTAGENA INDIAS 1; MEDELLIN 2",
    "ESTUDIO": "APROBACION DE 4 AÑOS DE PROFESIONAL EN NBC: CONTADURIA PUBLICA",
    "EXPERIENCIA": "24 MESES LABORAL",
	"FUNCIONES": `ASISTIR A LOS CONTRIBUYENTES, DECLARANTES, RESPONSABLES Y AGENTES DE RETENCION EN LOS TRAMITES COMPRENDIDOS EN LAS CAMPAÑAS REALIZADAS POR LA ENTIDAD Y DEMAS TRAMITES DEL PROCESO, DE CONFORMIDAD CON LA NORMATIVA, LINEAMIENTOS Y PROCEDIMIENTOS VIGENTES.
    ASISTIR TECNICA, OPERATIVA Y ADMINISTRATIVAMENTE LA GESTION A DESARROLLAR CON LAS ENTIDADES AUTORIZADAS PARA RECAUDAR, DE ACUERDO CON LA NORMATIVA, LINEAMIENTOS, PROCEDIMIENTOS Y COMPETENCIA.
    BRINDAR ASISTENCIA TECNICA, OPERATIVA Y ADMINISTRATIVA EN EL DESARROLLO DEL PROCEDIMIENTO DE DEVOLUCIONES Y O COMPENSACIONES, DE ACUERDO CON LA NORMATIVA VIGENTE, LA ASIGNACION, COMPETENCIA Y LINEAMIENTOS TECNICOS.
    CONTRIBUIR CON LA UNIFICACION DE LA INFORMACION SOBRE LAS OBLIGACIONES A NORMALIZAR Y LA REALIDAD FISCAL DEL CONTRIBUYENTE, DE CONFORMIDAD CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.
    DESARROLLAR LAS ACTIVIDADES DE COBRO PERSUASIVO DE LAS OBLIGACIONES FISCALES ADMINISTRADAS POR LA ENTIDAD QUE PERMITAN LA EXTINCION DE LA OBLIGACION O REMISION A COBRO COACTIVO Y DEMAS ACCIONES LEGALES, DE CONFORMIDAD CON EL PROCEDIMIENTO ESTABLECIDO Y GRADO DE RESPONSABILIDAD DEL EMPLEO.
    EJECUTAR ACTIVIDADES TECNICAS EN LA IDENTIFICACION DE NECESIDADES Y BUSQUEDA DE SOLUCIONES RELACIONADAS CON LA CREACION, MODIFICACION, OPERACION, AJUSTE, MANTENIMIENTO, PERMISOS DE ACCESO E IMPLANTACION DE LOS SISTEMAS DE INFORMACION CORPORATIVOS DE LOS PROCESOS DE ADMINISTRACION DE CARTERA Y RECAUDO, ASI COMO DE LA INFORMACION CONTENIDA EN ELLOS, DE CONFORMIDAD CON LAS POLITICAS, PLANES, PROCEDIMIENTOS, ESTANDARES INSTITUCIONALES VIGENTES, NIVEL Y GRADO DE RESPONSABILIDAD DEL EMPLEO.
    EJECUTAR LA SOLICITUD Y O CORRECCION DE DATOS INCONSISTENTES EN LAS DECLARACIONES, RECIBOS DE PAGO Y REPROCESO DE SALDOS REGISTRADOS EN LA ENTIDAD, DE ACUERDO CON LA NORMATIVA VIGENTE, EL PROCEDIMIENTO, LA COMPETENCIA Y EL GRADO DE RESPONSABILIDAD DEL EMPLEO.
    LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
    REALIZAR LA ACTUALIZACION DE LA CUENTA CORRIENTE CONTRIBUYENTE Y O OBLIGACION FINANCIERA, DE ACUERDO CON LA NORMATIVIDAD VIGENTE, LAS ASIGNACIONES, LINEAMIENTOS ESTABLECIDOS Y GRADO DE RESPONSABILIDAD DEL EMPLEO.
    TRAMITAR LA CLASIFICACION, PRIORIZACION Y DISTRIBUCION DE LA CARTERA, VERIFICACION Y ANALISIS DE LOS EXPEDIENTES, DE CONFORMIDAD CON LA NORMATIVA VIGENTE, LOS PROCEDIMIENTOS ESTABLECIDOS, LOS SISTEMAS INFORMATICOS DISPONIBLES Y LAS DIRECTRICES IMPARTIDAS.`
  },
  {
    "DENOMINACION": "ANALISTA II",
    "NIVEL": "TECNICO",
    "OPEC": "236596",
    "SALARIO": "$ 4,655,747.00",
    "VACANTES": "23",
    "CIUDADES": "IBAGUE 1; BOGOTA 10; BARRANQUILLA 3; MEDELLIN 1; CALI 1; BUCARAMANGA 3; TULUA 1; CARTAGENA INDIAS 1; VILLAVICENCIO 1; VALLEDUPAR 1",
    "ESTUDIO": "APROBACION DE 3 AÑOS DE PROFESIONAL EN NBC: CONTADURIA PUBLICA",
    "EXPERIENCIA": "12 MESES LABORAL",
	"FUNCIONES": `APOYAR LA EJECUCION DE DILIGENCIAS DE DESTRUCCION DE MERCANCIA AVERIADA, DEFECTUOSA O IMPROPIA RESPECTO DEL FIN PARA EL CUAL FUE IMPORTADA, DE ACUERDO CON LA NORMATIVA VIGENTE, LOS PROCEDIMIENTOS ESTABLECIDOS Y LAS DIRECTRICES INSTITUCIONALES.
APOYAR LA ORGANIZACION Y LOGISTICA REQUERIDA EN LA EJECUCION DE ACCIONES DE CONTROL, DE ACUERDO CON LOS LINEAMIENTOS INSTITUCIONALES.
APOYAR LA REALIZACION DE ACTIVIDADES DE VERIFICACION NECESARIAS DENTRO DE LAS INVESTIGACIONES TRIBUTARIAS, ADUANERAS O CAMBIARIAS, DE ACUERDO CON LA NORMATIVA VIGENTE, LAS DIRECTRICES INSTITUCIONALES Y LOS PROCEDIMIENTOS ESTABLECIDOS.
BRINDAR APOYO TECNICO Y ADMINISTRATIVO EN DILIGENCIAS, INVESTIGACIONES Y ACCIONES REQUERIDAS RESPECTO A OBLIGACIONES TRIBUTARIAS, ADUANERAS O CAMBIARIAS, ASI COMO DETECCION DE LAVADO DE ACTIVOS Y FINANCIACION DEL TERRORISMO, DE ACUERDO CON LA NORMATIVA VIGENTE, LOS PROCEDIMIENTOS ESTABLECIDOS Y LOS LINEAMIENTOS INSTITUCIONALES.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
REALIZAR LA GESTION DOCUMENTAL RELACIONADA CON TRAMITES, SOLICITUDES TECNICAS, DENUNCIAS Y REPORTES DE OPERACIONES SOSPECHOSAS, PROPIOS DEL PROCESO DE FISCALIZACION Y LIQUIDACION QUE PERMITAN ESTABLECER LA TRAZABILIDAD DE LO ACTUADO, DE ACUERDO CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.
REALIZAR VERIFICACIONES E INVENTARIOS DE MERCANCIAS SUJETAS A MEDIDAS CAUTELARES, DE ACUERDO CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.`
  },
  {
    "DENOMINACION": "ANALISTA II",
    "NIVEL": "TECNICO",
    "OPEC": "236653",
    "SALARIO": "$ 4,655,747.00",
    "VACANTES": "29",
    "CIUDADES": "IBAGUE 1; BOGOTA 11; POPAYAN 1; CARTAGENA INDIAS 1; VLLAVICENCIO 1; SOGAMOSO 1; CALI 3; BUCARAMANGA 1; BARRANQUILLA 4; MEDELLIN 1; BUENAVENTURA 1; PASTO 1; SANTA MARTA 1; CUCUTA 1",
    "ESTUDIO": "APROBACION DE 3 AÑOS DE PROFESIONAL EN NBC: CONTADURIA PUBLICA",
    "EXPERIENCIA": "12 MESES LABORAL",
	"FUNCIONES": `ADELANTAR ACTIVIDADES DE COBRO DE LAS OBLIGACIONES FISCALES ADMINISTRADAS POR LA ENTIDAD HASTA SU EXTINCION O REMISION A COBRO COACTIVO Y DEMAS ACCIONES LEGALES, DE CONFORMIDAD CON EL PROCEDIMIENTO ESTABLECIDO Y GRADO DE RESPONSABILIDAD DEL EMPLEO.
    APLICAR MECANISMOS DE ACTUALIZACION Y MONITOREO RELACIONADOS CON LA ACTUALIZACION DE LA CUENTA CORRIENTE CONTRIBUYENTE Y O OBLIGACION FINANCIERA, CORRECCION DE INCONSISTENCIAS DE LAS DECLARACIONES, RECIBOS DE PAGO Y REPROCESO DE SALDOS REGISTRADOS EN LA ENTIDAD, DE ACUERDO CON LA NORMATIVIDAD VIGENTE Y LOS LINEAMIENTOS ESTABLECIDOS.
    APOYAR EL DESARROLLO DEL PROCEDIMIENTO DE DEVOLUCIONES Y O COMPENSACIONES, DE ACUERDO CON LA NORMATIVA VIGENTE, LA ASIGNACION, COMPETENCIA, LINEAMIENTOS TECNICOS Y GRADO DE RESPONSABILIDAD DEL EMPLEO.
    ASISTIR TECNICA, OPERATIVA Y ADMINISTRATIVAMENTE LA GESTION A DESARROLLAR CON LAS ENTIDADES AUTORIZADAS PARA RECAUDAR, DE ACUERDO CON LA NORMATIVA, LINEAMIENTOS, PROCEDIMIENTOS Y COMPETENCIA.
    BRINDAR APOYO EN LA CLASIFICACION, PRIORIZACION Y DISTRIBUCION DE LA CARTERA, Y VERIFICACION DE LA INFORMACION DE LOS EXPEDIENTES, DE CONFORMIDAD CON LA NORMATIVA VIGENTE, LOS PROCEDIMIENTOS ESTABLECIDOS, LOS SISTEMAS INFORMATICOS DISPONIBLES Y LAS DIRECTRICES IMPARTIDAS.
    EJECUTAR ACTIVIDADES TECNICAS EN LA IDENTIFICACION DE NECESIDADES Y BUSQUEDA DE SOLUCIONES RELACIONADAS CON LA CREACION, MODIFICACION, OPERACION, AJUSTE, MANTENIMIENTO, PERMISOS DE ACCESO E IMPLANTACION DE LOS SISTEMAS DE INFORMACION CORPORATIVOS DE LOS SUBPROCESOS DE ADMINISTRACION DE CARTERA Y RECAUDACION, ASI COMO DE LA INFORMACION CONTENIDA EN ELLOS, DE CONFORMIDAD CON LAS POLITICAS, PLANES, PROCEDIMIENTOS, ESTANDARES INSTITUCIONALES VIGENTES, NIVEL Y GRADO DE RESPONSABILIDAD DEL EMPLEO.
    LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
    ORIENTAR A LOS CONTRIBUYENTES, DECLARANTES, RESPONSABLES Y AGENTES DE RETENCION A TRAVES DE LOS MEDIOS DISPUESTOS POR LA ENTIDAD EN RELACION CON LOS PASOS A SEGUIR FRENTE UN REQUERIMIENTO DE CONTROL DE OBLIGACIONES O FRENTE A LOS TRAMITES A SEGUIR EN LAS CAMPAÑAS REALIZADAS POR LA ENTIDAD, DE ACUERDO CON LA NORMATIVA VIGENTE, LOS PROCEDIMIENTOS Y DIRECTRICES DE NIVEL CENTRAL.
    PRESTAR APOYO EN LA UNIFICACION DE LA INFORMACION SOBRE LAS OBLIGACIONES A NORMALIZAR Y LA REALIDAD FISCAL DEL CONTRIBUYENTE, DE CONFORMIDAD CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.
    TRAMITAR LA CORRECCION DE INCONSISTENCIAS DE LAS DECLARACIONES, RECIBOS DE PAGO Y REPROCESO DE SALDOS REGISTRADOS EN LA ENTIDAD, DE ACUERDO CON LA NORMATIVA VIGENTE, EL PROCEDIMIENTO Y LA COMPETENCIA.`
  },
  {
    "DENOMINACION": "GESTOR I",
    "NIVEL": "PROFESIONAL",
    "OPEC": "236665",
    "SALARIO": "$ 6,811,546.00",
    "VACANTES": "6",
    "CIUDADES": "BOGOTA 1; NEIVA 1; BUCARAMANGA 1; BARRANQULLA 1; CARTAGENA INDIAS 1; MONTERIA 1",
    "ESTUDIO": "PROFESIONAL EN NBC: CONTADURIA PUBLICA",
    "EXPERIENCIA": "NO REQUIERE EXPERIENCIA",
	"FUNCIONES": `APLICAR MECANISMOS DE CONTROL EN EL CUMPLIMIENTO DE LAS OBLIGACIONES TRIBUTARIAS DE LOS AUTORRETENEDORES O GRANDES CONTRIBUYENTES O AGENTES RETENEDORES DE IVA, DE ACUERDO A SU COMPETENCIA, PROCEDIMIENTO Y NORMATIVA VIGENTE.
    ATENDER LAS ACCIONES RELACIONADAS CON LA INCORPORACION, LA CALIDAD Y LA UNIFICACION DE LA INFORMACION SOBRE LAS OBLIGACIONES A NORMALIZAR Y LA REALIDAD FISCAL DEL CONTRIBUYENTE, DE CONFORMIDAD CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.
    ATENDER LAS SOLICITUDES DE DEVOLUCIONES Y O COMPENSACIONES DE LOS DISTINTOS IMPUESTOS ADMINISTRADOS POR LA ENTIDAD, LA DISPOSICION DE RECURSOS Y GESTION DEL PAGO, DE CONFORMIDAD CON LA NORMATIVA VIGENTE Y LOS LINEAMIENTOS DE LA DEPENDENCIA COMPETENTE, LAS ASIGNACIONES Y GRADO DE RESPONSABILIDAD DEL EMPLEO.
    ATENDER LOS REQUERIMIENTOS DERIVADOS DE LOS PROGRAMAS MASIVOS DEL CONTROL Y CAMPAÑAS DE EJECUCION INMEDIATA Y DE AMPLIA COBERTURA QUE INCENTIVEN Y REQUIERAN EL CUMPLIMIENTO DE OBLIGACIONES FORMALES Y SUSTANCIALES, DE ACUERDO A LA NORMATIVA VIGENTE, LOS PROCEDIMIENTOS E INSTRUCCIONES IMPARTIDAS.
    CONTRIBUIR CON EL DESARROLLO DE LAS AUDITORIAS, CAPACITACIONES, SOPORTE TECNICO Y ADMINISTRATIVO EN LA GESTION CON LAS ENTIDADES RECAUDADORAS AUTORIZADAS, DE ACUERDO CON LA NORMATIVA, PROCEDIMIENTOS, LINEAMIENTOS ESTABLECIDOS Y COMPETENCIA.
    CORREGIR LOS DATOS INCONSISTENTES DE LAS DECLARACIONES, RECIBOS DE PAGO Y REPROCESO DE SALDOS REGISTRADOS EN LA ENTIDAD DE CONFORMIDAD CON EL PROCEDIMIENTO, LA COMPETENCIA Y LA NORMATIVA VIGENTE.
    DETERMINAR LA EXIGIBILIDAD Y REALIDAD DE LA OBLIGACION, ASI COMO LA ACTUALIZACION DE LA CUENTA CORRIENTE CONTRIBUYENTE Y O OBLIGACION FINANCIERA, DE ACUERDO CON LA NORMATIVIDAD VIGENTE, LA COMPETENCIA Y LOS LINEAMIENTOS ESTABLECIDOS Y GRADO DE RESPONSABILIDAD DEL EMPLEO.
    GESTIONAR HASTA SU CULMINACION LAS ACCIONES DE COBRO PERSUASIVO Y COACTIVO ASIGNADAS QUE CONLLEVE A EXTINGUIR LA OBLIGACION FISCAL, DE CONFORMIDAD CON LA NORMATIVA, EL PROCEDIMIENTO Y EL GRADO DE RESPONSABILIDAD DEL EMPLEO.
    GESTIONAR LA CREACION, IMPLANTACION, AJUSTE Y MANTENIMIENTO DE LOS SISTEMAS DE INFORMACION CORPORATIVOS DE LOS SUBPROCESOS DE RECAUDACION Y ADMINISTRACION DE CARTERA, DE CONFORMIDAD CON LAS POLITICAS ESTABLECIDAS, PROCEDIMIENTOS VIGENTES, PLANES Y NECESIDADES INSTITUCIONALES.
    LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
    REPRESENTAR A LA UAE DIAN EN LOS PROCESOS ESPECIALES Y O CONCURSALES, DE CONFORMIDAD CON LA NORMATIVA, LOS PROCEDIMIENTOS ESTABLECIDOS Y LA COMPETENCIA PROFESIONAL.`
  },
  {
    "DENOMINACION": "GESTOR I",
    "NIVEL": "PROFESIONAL",
    "OPEC": "236689",
    "SALARIO": "$ 6,811,546.00",
    "VACANTES": "3",
    "CIUDADES": "BOGOTA 3",
    "ESTUDIO": "PROFESIONAL EN NBC: CONTADURIA PUBLICA",
    "EXPERIENCIA": "NO REQUIERE EXPERIENCIA",
	"FUNCIONES": `REALIZAR ACCIONES QUE PERMITAN LA EVALUACION DEL SISTEMA DE CONTROL INTERNO, DE CONFORMIDAD CON LA NORMATIVIDAD VIGENTE, LOS PROCEDIMIENTOS ESTABLECIDOS Y LINEAMIENTOS INSTITUCIONALES.
    EVIDENCIAR Y COMUNICAR LAS ACCIONES DE MEJORA DEL SISTEMA DE CONTROL INTERNO DE LA ENTIDAD, DE CONFORMIDAD CON LA NORMATIVIDAD VIGENTE Y LINEAMIENTOS INSTITUCIONALES.
    PARTICIPAR EN EL DESARROLLO DE LAS AUDITORIAS, EVALUACIONES Y ELABORACION DE INFORMES DE LEY DEL PLAN ANUAL DE AUDITORIA DE ACUERDO CON LA NORMATIVIDAD VIGENTE LINEAMIENTOS Y PROCEDIMIENTOS INSTITUCIONALES.
    LLEVAR A CABO ESTRATEGIAS, METODOLOGIAS, HERRAMIENTAS Y TECNICAS PARA LA EVALUACION Y MEJORAMIENTO DE LA GESTION DE LOS RIESGOS Y CONTROLES DE ACUERDO CON LAS NORMAS INTERNACIONALES DE AUDITORIA INTERNA Y NORMATIVIDAD VIGENTE.
    REALIZAR ACCIONES ENCAMINADAS AL SEGUIMIENTO DE LOS PLANES DE MEJORAMIENTO, EN CUANTO A LA PERTINENCIA Y NIVEL DE AVANCE DE ACUERDO CON LA NORMATIVIDAD VIGENTE, LINEAMIENTOS Y PROCEDIMIENTOS INSTITUCIONALES.
    PARTICIPAR DE LAS ACTIVIDADES, PROGRAMAS Y HERRAMIENTAS ORIENTADAS A LA PROMOCION DE LA CULTURA DE CONTROL Y MEJORAMIENTO CONTINUO DE ACUERDO CON POLITICAS , PLANES, OBJETIVOS Y LOS LINEAMIENTOS INSTITUCIONALES.
    ACOMPAÑAR A LAS DEPENDENCIAS EN LA RESPUESTA ENTRE LA ENTIDAD, ENTES DE CONTROL Y PARTES INTERESADAS INTERNAS Y EXTERNAS A LOS REQUERIMIENTOS EFECTUADOS, CUMPLIENDO LOS CRITERIOS DE OPORTUNIDAD Y PERTINENCIA DE ACUERDO CON LA NORMATIVA VIGENTE, LOS LINEAMIENTOS Y PROCEDIMIENTOS INSTITUCIONALES.
    PARTICIPAR EN LA ELABORACION DE PROPUESTAS PARA EL MEJORAMIENTO DEL MODELO DE GESTION DE LA ENTIDAD, EN EL MARCO DE LA NORMATIVA VIGENTE, LAS POLITICAS GUBERNAMENTALES LOS PROCEDIMIENTOS VIGENTES Y LINEAMIENTOS INSTITUCIONALES.
    LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.`
  },
  {
    "DENOMINACION": "GESTOR I",
    "NIVEL": "PROFESIONAL",
    "OPEC": "236635",
    "SALARIO": "$ 6,811,546.00",
    "VACANTES": "2",
    "CIUDADES": "BOGOTA 2",
    "ESTUDIO": "PROFESIONAL EN NBC: CONTADURIA PUBLICA",
    "EXPERIENCIA": "NO REQUIERE EXPERIENCIA",
	"FUNCIONES": `APOYAR METODOLOGICAMENTE LA GESTION DE RIESGOS, SELECTIVIDAD ADUANERA Y CONSTRUCCION DE PERFILES DE RIESGO, DE ACUERDO CON LOS LINEAMIENTOS Y PROCEDIMIENTOS ESTABLECIDOS Y EL GRADO DE RESPONSABILIDAD DEL EMPLEO.
CONSOLIDAR LA INFORMACION PARA EL ANALISIS DE LOS FOCOS DE EVASION, CONTRABANDO Y DE LAS PRINCIPALES INFRACCIONES A LOS REGIMENES TRIBUTARIO, ADUANERO Y CAMBIARIO, DE ACUERDO CON LA NORMATIVA VIGENTE, LAS POLITICAS, LAS METODOLOGIAS Y LINEAMIENTOS ESTABLECIDOS.
CONSOLIDAR LA INFORMACION RELACIONADA CON EL DISEÑO DE PROGRAMAS, CAMPAÑAS Y ESTRATEGIAS DE CONTROL Y FACILITACION PARA EL CUMPLIMIENTO DE LAS OBLIGACIONES ADUANERAS, TRIBUTARIAS Y CAMBIARIAS, DE ACUERDO CON LA NORMATIVA VIGENTE, LAS POLITICAS INSTITUCIONALES Y LINEAMIENTOS ESTABLECIDOS.
CONSOLIDAR LA INFORMACION RELACIONADA CON LOS ESTUDIOS SOBRE LAS DIFERENTES INFRACCIONES A LOS REGIMENES TRIBUTARIO, ADUANERO Y CAMBIARIO, DE ACUERDO CON LA NORMATIVA VIGENTE.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
REALIZAR PROYECTOS DE INVESTIGACION EN MATERIA DE PROGRAMAS, CAMPAÑAS Y RIESGO TRIBUTARIO, ADUANERO Y CAMBIARIO SOBRE LA GESTION DE RIESGOS, SELECTIVIDAD ADUANERA Y PERFILES DE RIESGO, DE ACUERDO CON LAS MEJORES PRACTICAS INTERNACIONALES, POLITICAS GUBERNAMENTALES Y LAS NECESIDADES INSTITUCIONALES.
UTILIZAR LAS METODOLOGIAS ESTABLECIDAS PARA LA GESTION DE RIESGOS, SELECTIVIDAD ADUANERA Y LA CONSTRUCCION DE PERFILES DE RIESGO Y SELECTIVIDAD DE ACUERDO CON LOS LINEAMIENTOS Y PROCEDIMIENTOS ESTABLECIDOS.`
  },
  {
    "DENOMINACION": "GESTOR I",
    "NIVEL": "PROFESIONAL",
    "OPEC": "242574",
    "SALARIO": "$ 6,811,546.00",
    "VACANTES": "1",
    "CIUDADES": "BOGOTA 1",
    "ESTUDIO": "PROFESIONAL EN NBC: CONTADURIA PUBLICA",
    "EXPERIENCIA": "NO REQUIERE EXPERIENCIA",
	"FUNCIONES": `ADELANTAR LAS ACCIONES NECESARIAS PARA ELABORAR EL ANTEPROYECTO DEL PRESUPUESTO DE LA DIRECCION SECCIONAL, DE ACUERDO CON LAS DIRECTRICES DEL NIVEL CENTRAL.
CONTABILIZAR LOS INGRESOS ADMINISTRADOS POR LA ENTIDAD, DE ACUERDO CON LOS PROCEDIMIENTOS, LA NORMATIVA APLICABLE Y LA COMPETENCIA DEL AREA.
EJECUTAR EFICIENTEMENTE EL PLAN ANUAL MENSUALIZADO DE CAJA, GARANTIZANDO EL CUMPLIMIENTO DE LAS OBLIGACIONES CONTRAIDAS POR LA ENTIDAD, DE ACUERDO CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS, SEGUN SEA SU COMPETENCIA.
EJECUTAR LAS ACCIONES NECESARIAS PARA EL ADECUADO FUNCIONAMIENTO DE LA CAJA MENOR, DE ACUERDO CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.
EJECUTAR LAS ACCIONES NECESARIAS PARA LA GESTION DE LOS APORTES Y DEDUCCIONES QUE REALIZAN LOS FUNCIONARIOS Y CONTRATISTAS DE LA ENTIDAD, DE ACUERDO CON LOS PROCEDIMIENTOS Y NORMATIVA VIGENTE , SEGUN SEA SU COMPETENCIA.
ELABORAR LAS DECLARACIONES TRIBUTARIAS A CARGO DEL PROCESO ADMINISTRATIVO Y FINANCIERO, DE ACUERDO CON LA NORMATIVA VIGENTE Y EL PROCEDIMIENTO ESTABLECIDO.
ELABORAR LOS INFORMES FINANCIEROS DE LA ENTIDAD Y LOS REPORTES A PRESENTAR ANTE LOS ENTES DE CONTROL, DE ACUERDO A LA NORMATIVA VIGENTE Y LA REALIDAD ECONOMICA DE LA ENTIDAD.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
REALIZAR CONCILIACIONES Y CRUCES DE INFORMACION RELACIONADOS CON LAS OPERACIONES ECONOMICAS GENERADAS CON OTRAS ENTIDADES QUE SE CONSIDERAN RECIPROCAS, DE ACUERDO CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.
REALIZAR ACCIONES DE REGISTRO, TRAMITE Y CONTROL DE AUTORIZACIONES DE EFECTIVO CORRESPONDIENTE A DEVOLUCIONES Y SITUACION DE FONDOS DEL FONDO ROTATORIO DE DEVOLUCIONES, DE ACUERDO A LOS LINEAMIENTOS, PROCEDIMIENTOS, NORMATIVA VIGENTE Y LA COMPETENCIA DEL AREA.
REALIZAR LAS ACCIONES NECESARIAS PARA EL RECONOCIMIENTO DE LOS REINTEGROS E INGRESOS EN LOS SISTEMAS DE INFORMACION, DE ACUERDO CON LOS PROCEDIMIENTOS Y LA NORMATIVIDAD APLICABLE VIGENTE.
REALIZAR LAS ACCIONES NECESARIAS PARA EL RECONOCIMIENTO Y ANALISIS DE LOS HECHOS ECONOMICOS, TALES COMO CERTIFICADO DE DISPONIBILIDAD PRESUPUESTAL, REGISTRO PRESUPUESTAL, REGISTRO DE RESERVAS, OBLIGACIONES PRESUPUESTALES, ORDENES DE PAGO, ETC., EN LOS SISTEMAS DE INFORMACION FINANCIERA, DE ACUERDO CON LOS PROCEDIMIENTOS Y LA NORMATIVIDAD APLICABLE VIGENTE.
REALIZAR LAS ACCIONES NECESARIAS PARA LA VERIFICACION Y CONCILIACION DE LA INFORMACION QUE GENERAN LAS DIFERENTES AREAS DE LA ENTIDAD Y QUE DEBE RECONOCERSE EN LA CONTABILIDAD, DE ACUERDO CON LOS PROCEDIMIENTOS Y NORMATIVA VIGENTE.`
  },
  {
    "DENOMINACION": "ANALISTA V",
    "NIVEL": "TECNICO",
    "OPEC": "236591",
    "SALARIO": "$ 7,171,627.00",
    "VACANTES": "6",
    "CIUDADES": "BOGOTA 1; IPIALES 1; SANTA MARTA 1; BUCARAMANGA 2; BUENAVENTURA 1",
    "ESTUDIO": "TERMINACION Y APROBACION DE PENSUM EDUCACION SUPERIOR DE PROFESIONAL EN NBC: CONTADURIA PUBLICA",
    "EXPERIENCIA": "25 MESES LABORAL Y 12 MESES RELACIONADA",
	"FUNCIONES": `ACOMPAÑAR LAS DILIGENCIAS DE PRACTICA DE PRUEBAS DECRETADAS DENTRO DE UNA INVESTIGACION, DE ACUERDO CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.
APOYAR LA EJECUCION DE ACCIONES DE FISCALIZACION, EN EL MARCO DE SU COMPETENCIA Y JURISDICCION, TENDIENTES A LA VERIFICACION DEL CUMPLIMIENTO DE LAS OBLIGACIONES TRIBUTARIAS, ADUANERAS O CAMBIARIAS, DE ACUERDO CON LA NORMATIVA VIGENTE, LINEAMIENTOS INSTITUCIONALES Y PROCEDIMIENTOS ESTABLECIDOS.
CLASIFICAR LA INFORMACION NECESARIA PARA EL ANALISIS PRELIMINAR DE LOS INSUMOS Y DE LAS DENUNCIAS DE FISCALIZACION RECIBIDAS, DE ACUERDO CON LA NORMATIVA VIGENTE, PROCEDIMIENTOS Y LINEAMIENTOS INSTITUCIONALES.
DESARROLLAR ACCIONES TECNICAS Y ADMINISTRATIVAS QUE FACILITEN LA EJECUCION DE LOS PROCEDIMIENTOS ASOCIADOS AL PROCESO DE FISCALIZACION Y LIQUIDACION, DE ACUERDO CON LA NORMATIVA, LAS POLITICAS Y LOS LINEAMIENTOS ESTABLECIDOS.
DESARROLLAR ACTIVIDADES DE APOYO PARA LA REALIZACION DE ESTUDIOS E INVESTIGACIONES QUE SIRVAN DE BASE EN LA ELABORACION DE PROPUESTAS DE PROGRAMAS Y ACCIONES DE CONTROL, DE ACUERDO CON LA NORMATIVA VIGENTE Y SEGUN DIRECTRICES INSTITUCIONALES.
DESARROLLAR ACTIVIDADES DE VERIFICACION NECESARIAS DENTRO DE LAS INVESTIGACIONES PARA LA DETERMINACION DEL CUMPLIMIENTO DE LAS OBLIGACIONES TRIBUTARIAS, ADUANERAS O CAMBIARIAS Y, EL REPORTE DE LAS OPERACIONES SOSPECHOSAS DE LAVADO DE ACTIVOS Y FINANCIACION DEL TERRORISMO, EN EL MARCO DE SU COMPETENCIA Y JURISDICCION, DE ACUERDO CON LA NORMATIVA VIGENTE, LAS DIRECTRICES INSTITUCIONALES Y LOS PROCEDIMIENTOS ESTABLECIDOS.
ELABORAR ACTOS ADMINISTRATIVOS Y DEMAS DOCUMENTOS DE CARACTER TECNICO, ADMINISTRATIVO Y OPERATIVO RELACIONADOS CON ASUNTOS DEL PROCESO DE FISCALIZACION Y LIQUIDACION, DE ACUERDO CON LA NORMATIVA Y PROCEDIMIENTOS VIGENTES.
INTERVENIR EN LAS DILIGENCIAS DE DESTRUCCION DE MERCANCIA AVERIADA, DEFECTUOSA O IMPROPIA RESPECTO DEL FIN PARA EL CUAL FUE IMPORTADA, DE ACUERDO CON LA NORMATIVA VIGENTE, LOS PROCEDIMIENTOS ESTABLECIDOS Y LAS DIRECTRICES INSTITUCIONALES.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
REALIZAR LA GESTION DOCUMENTAL RELACIONADA CON TRAMITES, SOLICITUDES TECNICAS, DENUNCIAS Y REPORTES DE OPERACIONES SOSPECHOSAS, PROPIOS DEL PROCESO DE FISCALIZACION Y LIQUIDACION QUE PERMITAN ESTABLECER LA TRAZABILIDAD DE LO ACTUADO, DE ACUERDO CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.`
  },
  {
    "DENOMINACION": "ANALISTA IV",
    "NIVEL": "TECNICO",
    "OPEC": "236592",
    "SALARIO": "$ 6,390,426.00",
    "VACANTES": "13",
    "CIUDADES": "BOGOTA 3; GIRARDOT 1; CARTAGENA IINDIAS 1; PASTO 1; MEDELLIN 1; VILLAVICENCIO 1; PEREIRA 1; BARRANQUILLA 2; CUCUTA 2",
    "ESTUDIO": "TERMINACION Y APROBACION DE PENSUM EDUCACION SUPERIOR DE PROFESIONAL EN NBC: CONTADURIA PUBLICA",
    "EXPERIENCIA": "36 MESES LABORAL",
	"FUNCIONES": `ACOMPAÑAR LAS DILIGENCIAS DE PRACTICA DE PRUEBAS DECRETADAS DENTRO DE UNA INVESTIGACION, DE ACUERDO CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.
APOYAR LA EJECUCION DE ACCIONES DE FISCALIZACION, EN EL MARCO DE SU COMPETENCIA Y JURISDICCION, TENDIENTES A LA VERIFICACION DEL CUMPLIMIENTO DE LAS OBLIGACIONES TRIBUTARIAS, ADUANERAS O CAMBIARIAS, DE ACUERDO CON LA NORMATIVA VIGENTE, LINEAMIENTOS INSTITUCIONALES Y PROCEDIMIENTOS ESTABLECIDOS.
CLASIFICAR LA INFORMACION NECESARIA PARA EL ANALISIS PRELIMINAR DE LOS INSUMOS Y DE LAS DENUNCIAS DE FISCALIZACION RECIBIDAS, DE ACUERDO CON LA NORMATIVA VIGENTE, PROCEDIMIENTOS Y LINEAMIENTOS INSTITUCIONALES.
ELABORAR ACTOS ADMINISTRATIVOS Y DEMAS DOCUMENTOS DE CARACTER TECNICO, ADMINISTRATIVO Y OPERATIVO RELACIONADOS CON ASUNTOS DEL PROCESO DE FISCALIZACION Y LIQUIDACION, DE ACUERDO CON LA NORMATIVA Y PROCEDIMIENTOS VIGENTES.
INTERVENIR EN LAS DILIGENCIAS DE DESTRUCCION DE MERCANCIA AVERIADA, DEFECTUOSA O IMPROPIA RESPECTO DEL FIN PARA EL CUAL FUE IMPORTADA, DE ACUERDO CON LA NORMATIVA VIGENTE, LOS PROCEDIMIENTOS ESTABLECIDOS Y LAS DIRECTRICES INSTITUCIONALES.
LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
PARTICIPAR EN LAS ACCIONES TECNICAS Y ADMINISTRATIVAS QUE FACILITEN LA EJECUCION DE LOS PROCEDIMIENTOS ASOCIADOS AL PROCESO DE FISCALIZACION Y LIQUIDACION, DE ACUERDO CON LA NORMATIVA, LAS POLITICAS Y LOS LINEAMIENTOS ESTABLECIDOS.
REALIZAR ACTIVIDADES DE VERIFICACION NECESARIAS DENTRO DE LAS INVESTIGACIONES PARA LA DETERMINACION DEL CUMPLIMIENTO DE LAS OBLIGACIONES TRIBUTARIAS, ADUANERAS O CAMBIARIAS Y, EL REPORTE DE LAS OPERACIONES SOSPECHOSAS DE LAVADO DE ACTIVOS Y FINANCIACION DEL TERRORISMO, EN EL MARCO DE SU COMPETENCIA Y JURISDICCION, DE ACUERDO CON LA NORMATIVA VIGENTE, LAS DIRECTRICES INSTITUCIONALES Y LOS PROCEDIMIENTOS ESTABLECIDOS.
REALIZAR LA GESTION DOCUMENTAL RELACIONADA CON TRAMITES, SOLICITUDES TECNICAS, DENUNCIAS Y REPORTES DE OPERACIONES SOSPECHOSAS, PROPIOS DEL PROCESO DE FISCALIZACION Y LIQUIDACION QUE PERMITAN ESTABLECER LA TRAZABILIDAD DE LO ACTUADO, DE ACUERDO CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.`
  },
  {
    "DENOMINACION": "GESTOR II",
    "NIVEL": "PROFESIONAL",
    "OPEC": "236566",
    "SALARIO": "$ 7,988,200.00",
    "VACANTES": "67",
    "CIUDADES": "IBAGUÉ 7; BOGOTA 17; NEIVA 2; VALLEDUPAR 3; CARTAGENA INDIAS 4; ARMENIA 3; RIOHACHA 1; MANIZALES 2; TULUA 1; MEDELLIN 5; FLORENCIA 1; BARRANQUILLA 2; SOGAMOSO 1; CALI 2; BUCARAMANGA 3; SAN ANDRES 2; SINCELEJO 3; VILLAVICENCIO 1; PEREIRA 5; PASTO 1; QUIBDO 1",
    "ESTUDIO": "PROFESIONAL EN NBC: CONTADURIA PUBLICA",
    "EXPERIENCIA": "12 MESES PROFESIONAL",
	"FUNCIONES": `ADELANTAR LAS DILIGENCIAS DE LOS PROCESOS QUE LE SEAN ASIGNADOS RELACIONADOS CON LA ADMINISTRACION DE CARTERA, DE CONFORMIDAD CON LA NORMATIVA VIGENTE, LOS PROCEDIMIENTOS ESTABLECIDOS Y EL GRADO DE RESPONSABILIDAD DEL EMPLEO.
    APLICAR MECANISMOS DE CONTROL EN EL CUMPLIMIENTO DE LAS OBLIGACIONES TRIBUTARIAS DE LOS AUTORRETENEDORES O GRANDES CONTRIBUYENTES O AGENTES RETENEDORES DE IVA, DE ACUERDO A SU COMPETENCIA, PROCEDIMIENTO Y NORMATIVA VIGENTE.
    CORREGIR LOS DATOS INCONSISTENTES DE LAS DECLARACIONES, RECIBOS DE PAGO Y REPROCESO DE SALDOS REGISTRADOS EN LA ENTIDAD DE CONFORMIDAD CON EL PROCEDIMIENTO, LA COMPETENCIA Y LA NORMATIVA VIGENTE.
    DESARROLLAR AUDITORIAS, CAPACITACIONES, VERIFICACION DE REQUISITOS Y SEGUIMIENTO A LAS ENTIDADES RECAUDADORAS AUTORIZADAS, ASI COMO LA APLICACION DE SANCIONES, DE ACUERDO CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.
    DESARROLLAR CAMPAÑAS DE EJECUCION INMEDIATA Y DE AMPLIA COBERTURA QUE INCENTIVEN Y REQUIERAN EL CUMPLIMIENTO DE LAS OBLIGACIONES FORMALES Y SUSTANCIALES, DE LAS PERSONAS NATURALES Y JURIDICAS OBLIGADAS POR LEY O QUE SON SUJETO DE LAS OBLIGACIONES ADMINISTRADAS POR LA ENTIDAD, DE CONFORMIDAD CON LA NORMATIVA, LINEAMIENTOS Y PROCEDIMIENTOS VIGENTES .
    GESTIONAR LA CREACION, MODIFICACION, AJUSTE, MANTENIMIENTO, OPERACION, PERMISOS DE ACCESO E IMPLANTACION DE LOS SISTEMAS DE INFORMACION CORPORATIVOS DE LOS SUBPROCESOS DE RECAUDACION Y ADMINISTRACION DE CARTERA, ASI COMO DE LA INFORMACION CONTENIDA EN ELLOS, DE CONFORMIDAD CON LAS POLITICAS, PLANES, PROCEDIMIENTOS, ESTANDARES INSTITUCIONALES VIGENTES, NIVEL Y GRADO DE RESPONSABILIDAD DEL EMPLEO.
    LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
    REALIZAR LAS ACTIVIDADES TENDIENTES A DEPURAR LA INFORMACION DEL ESTADO DE CUENTA DEL CONTRIBUYENTE, ASI COMO DE LA EXIGIBILIDAD Y REALIDAD DE LA OBLIGACION, DE CONFORMIDAD CON LA NORMATIVA Y PROCEDIMIENTOS VIGENTES.
    REPRESENTAR A LA UAE DIAN EN LOS PROCESOS ESPECIALES Y O CONCURSALES, DE CONFORMIDAD CON LA NORMATIVA, LOS PROCEDIMIENTOS ESTABLECIDOS Y LA COMPETENCIA PROFESIONAL.
    RESPONDER POR LA INCORPORACION, LA CALIDAD Y LA UNIFICACION DE LA INFORMACION SOBRE LAS OBLIGACIONES A NORMALIZAR Y LA REALIDAD FISCAL DEL CONTRIBUYENTE, DE CONFORMIDAD CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.
    TRAMITAR LAS SOLICITUDES DE DEVOLUCIONES Y O COMPENSACIONES DE LOS DISTINTOS IMPUESTOS ADMINISTRADOS POR LA ENTIDAD, LA DISPOSICION DE RECURSOS Y LA GESTION DEL PAGO, DE CONFORMIDAD CON LA NORMATIVA VIGENTE, LOS LINEAMIENTOS DE LA DEPENDENCIA COMPETENTE Y NIVEL DE RESPONSABILIDAD DEL EMPLEO.`
  },
  {
    "DENOMINACION": "GESTOR III",
    "NIVEL": "PROFESIONAL",
    "OPEC": "236664",
    "SALARIO": "$ 9,346,562.00",
    "VACANTES": "33",
    "CIUDADES": "IBAGUE 2; BOGOTA 9; TUNJA 1; BARRANQUILLA 1; BARRANCABERMEJA 1; VILLAVICENCIO 1; MEDELLIN 8; PEREIRA 1; SOGAMOSO 2; SANTA MARTA 1; PASTO 1; MONTERIA 2; CARTAGENA INDIAS 1; RIOHACHA 1; NEIVA 1",
    "ESTUDIO": "PROFESIONAL EN NBC: CONTADURIA PUBLICA",
    "EXPERIENCIA": "12 MESES PROFESIONAL Y 12 MESES PROFESIONAL RELACIONADA",
	"FUNCIONES": `APLICAR MECANISMOS DE CONTROL EN EL CUMPLIMIENTO DE LAS OBLIGACIONES TRIBUTARIAS DE LOS AUTORRETENEDORES O GRANDES CONTRIBUYENTES O AGENTES RETENEDORES DE IVA, DE ACUERDO A SU COMPETENCIA, PROCEDIMIENTO Y NORMATIVA VIGENTE.
    CORREGIR LOS DATOS INCONSISTENTES DE LAS DECLARACIONES, RECIBOS DE PAGO Y REPROCESO DE SALDOS REGISTRADOS EN LA ENTIDAD, DE CONFORMIDAD CON LA NORMATIVA VIGENTE, EL PROCEDIMIENTO Y LA COMPETENCIA.
    DESARROLLAR ACCIONES DE DISEÑO Y EJECUCION DE CAMPAÑAS INMEDIATAS O PROGRAMAS MASIVOS QUE INCENTIVEN Y REQUIERAN EL CUMPLIMIENTO DE LAS OBLIGACIONES FORMALES Y SUSTANCIALES EN LAS PERSONAS NATURALES Y JURIDICAS OBLIGADAS POR LEY O QUE SON SUJETO DE LAS OBLIGACIONES ADMINISTRADAS POR LA ENTIDAD, DE CONFORMIDAD CON LA NORMATIVA, LINEAMIENTOS Y PROCEDIMIENTOS VIGENTES.
    DESARROLLAR LA VERIFICACION DE REQUISITOS DE LAS ENTIDADES RECAUDADORAS AUTORIZADAS PARA SU AUTORIZACION, ASI COMO LA REALIZACION DE AUDITORIAS, CAPACITACIONES,CONTROL Y SANCION, DE ACUERDO CON LA NORMATIVA VIGENTE Y LOS PROCEDIMIENTOS ESTABLECIDOS.
    DESARROLLAR LOS PROCEDIMIENTOS Y DILIGENCIAS RELACIONADAS CON EL SUBPROCESO DE ADMINISTRACION DE CARTERA QUE CONLLEVE A LA DEPURACION Y EXTINCION DE LA OBLIGACION FISCAL, DE ACUERDO CON EL REPARTO Y LA NORMATIVA VIGENTE.
    GARANTIZAR INCORPORACION Y LA CALIDAD DE LA INFORMACION SOBRE LA UNIFICACION DE SALDOS A NORMALIZAR Y LA REALIDAD FISCAL DEL CONTRIBUYENTE, DE CONFORMIDAD CON LA NORMATIVA Y PROCEDIMIENTOS VIGENTES.
    GESTIONAR LA CREACION, MODIFICACION, AJUSTE, MANTENIMIENTO, OPERACION, PERMISOS DE ACCESO E IMPLANTACION DE LOS SISTEMAS DE INFORMACION CORPORATIVOS DE LOS SUBPROCESOS DE RECAUDACION Y ADMINISTRACION DE CARTERA, ASI COMO DE LA INFORMACION CONTENIDA EN ELLOS, DE CONFORMIDAD CON LAS POLITICAS, PLANES, PROCEDIMIENTOS, ESTANDARES INSTITUCIONALES VIGENTES, NIVEL Y GRADO DE RESPONSABILIDAD DEL EMPLEO.
    GESTIONAR LAS SOLICITUDES DE DEVOLUCIONES Y O COMPENSACIONES DE LOS DISTINTOS IMPUESTOS ADMINISTRADOS POR LA ENTIDAD, LA DISPOSICION DE RECURSOS Y LA GESTION DEL PAGO, DE CONFORMIDAD CON LA NORMATIVA VIGENTE Y LOS LINEAMIENTOS DE LA DEPENDENCIA COMPETENTE.
    LAS SEÑALADAS COMO COMUNES A TODOS LOS EMPLEOS DE LA PLANTA DE PERSONAL DE LA ENTIDAD, INCLUIDAS EN LA RESOLUCION QUE ADOPTA O MODIFICA EL MANUAL Y LAS DEMAS ASIGNADAS POR AUTORIDAD COMPETENTE, DE ACUERDO CON EL NIVEL, GRADO DE RESPONSABILIDAD Y EL AREA DE DESEMPEÑO DEL EMPLEO.
    REALIZAR LAS ACTIVIDADES TENDIENTES A DEPURAR Y CLASIFICAR LA INFORMACION DEL ESTADO DE CUENTA DEL CONTRIBUYENTE, ASI COMO DE LA EXIGIBILIDAD Y REALIDAD DE LA OBLIGACION, DE CONFORMIDAD CON LA NORMATIVA Y PROCEDIMIENTOS VIGENTES.
    REPRESENTAR A LA UAE DIAN EN LOS PROCESOS ESPECIALES Y O CONCURSALES, DE CONFORMIDAD CON LA NORMATIVA, LOS PROCEDIMIENTOS ESTABLECIDOS Y LA COMPETENCIA PROFESIONAL.`
  }
]


const empleosContainer = document.querySelector("#empleos-container");

/**
 * Función auxiliar para convertir el texto largo de funciones en una lista (<ul>) de elementos (<li>).
 * @param {string} rawText El bloque de texto con saltos de línea.
 * @returns {HTMLUListElement} El elemento <ul> generado.
 */

function crearFuncionesLista(rawText) {
	const ul = document.createElement('ul');
    ul.classList.add('funciones-list');

    // Divide el texto por saltos de línea o por punto y seguido, luego filtra líneas vacías.
    const funcionesArray = rawText.split('\n').filter(line => line.trim() !== '');

    funcionesArray.forEach(funcText => {
        const li = document.createElement('li');
        li.textContent = funcText.trim();
        ul.appendChild(li);
    });

    return ul;
}

function crearEmpleo(item) {
	const card = document.createElement("div");
	card.classList.add("card");

	const titulo = document.createElement("h3");
	titulo.textContent = item.DENOMINACION;

	const subtitulo = document.createElement("p");
	subtitulo.classList.add("empleo-nivel");
	subtitulo.textContent = `Nivel ${item.NIVEL} | OPEC: ${item.OPEC}`;

	const detallesDiv = document.createElement("div");
	detallesDiv.classList.add("empleo-detalles");

	const salario = document.createElement("p");
	salario.classList.add("salario");
	salario.textContent = `Salario: ${item.SALARIO}`;

	const ciudades = document.createElement("p");
	ciudades.textContent = `Ciudades: ${item.CIUDADES}`;

	detallesDiv.appendChild(salario);
	detallesDiv.appendChild(ciudades);

	const requisitosDiv = document.createElement("div");
	requisitosDiv.classList.add("empleo-requisitos");

	const estudio = document.createElement("p");
	estudio.textContent = `Estudio: ${item.ESTUDIO}`;

	const experiencia = document.createElement("p");
	experiencia.textContent = `Experiencia: ${item.EXPERIENCIA}`;

	requisitosDiv.appendChild(estudio);
	requisitosDiv.appendChild(experiencia);

	const funcionesTitulo = document.createElement("h4");
	funcionesTitulo.textContent = "Funciones del Empleo";

    const funcionesLista = crearFuncionesLista(item.FUNCIONES || '');


	card.appendChild(titulo);
	card.appendChild(subtitulo);
	card.appendChild(detallesDiv);
	card.appendChild(requisitosDiv);
	card.appendChild(funcionesTitulo);
	card.appendChild(funcionesLista);

    return card;

}

data.forEach(empleo => {
    const empleoCard = crearEmpleo(empleo);
    empleosContainer.appendChild(empleoCard);
})
